### ISSUE TITLE
Cmd/Shift/ctrl click functions

### ISSUE THREAD

**Issue by tslomkajr** [mattanger/ckb-next#103]
Key comands work when combining keys like cmd+shift+n for a new folder in finder, or cmd+a to select all however, using the cmd/shift/ctrl keys + left click does not work for any of their functions. 
I cannot ctrl+click for a right click. Cannot cmd+click to select multiple files. Cannot shift+click to select all files between first selected file and last. Cannot cmd+click on a link to open in a new tab. I think you get the point. I didn't see this as a known error but I hope there is a way to fix this because I think it is an essential part of my keyboard usage.

**Comment by ghost** [comment]
> On newer versions of macOS (i.e. 10.12 and up) CMD/Shift+select does not work, yet. Stopping the daemon and GUI for ckb will fix this issue temporarily.

In other words, don't use this software just for now.

Merged into #29.
