### ISSUE TITLE
k65 LUX RGB Not detected.

### ISSUE THREAD

**Issue by startupfoundry** [mattanger/ckb-next#105]
Hello, I've built the most recent version of ckb-next but I am unable to detect my k65 LUX RGB. I'm on OS X 10.12.3.

![k65lux](https://cloud.githubusercontent.com/assets/3033510/23581047/04d5c9ba-00db-11e7-80de-283cefe5e8af.png)

**Comment by frickler24** [comment]
@startupfoundry if you have got the current master branch from ckb-next, you should have ckb-next 0.2.7, not ckb 0.2.4

**Comment by vagrant10** [comment]
Hi, I'm also thinking of getting a k65 Lux RGB, however just to check if cbk-next will work (functional including RGB), as it's not listed in the supported list. 

Background - Sierra 10.12.2 and my country doesnt sell K65 RGB anymore. 

Thanks everyone!

**Comment by ghost** [comment]
@vagrant10 see #2. If you don't have a device and can't provide any information, just press the "Subscribe" button and wait. We have no ETAs, so there's that.

**Comment by ghost** [comment]
@startupfoundry excuse me, I was distracted by @vagrant10.
And yes, @frickler24 is right, you are using the old ckb, current master branch looks like that:

![screenshot from 2017-03-06 22-39-02](https://cloud.githubusercontent.com/assets/10786469/23631129/ccb59fd0-02bd-11e7-8a54-7b99d215719a.png)

Try at least it and if no success, try `testing`.

Then report back.

**Comment by auibrian** [comment]
@startupfoundry Make sure you are running the ckb-daemon, I have a k65 RGB and it works fine (barring the issues listed on github here)

**Comment by startupfoundry** [comment]
I got it working. Thanks for your comments. I literally just built it from source again (the same way as I did previously) and it worked.

**Comment by mik115** [comment]
hi @auibrian,
i've the same problem of @startupfoundry but i've installed the latest version of ckb-next and i have a k65 rgb rapidfire.

![screen shot 2017-03-13 at 13 14 27](https://cloud.githubusercontent.com/assets/2995032/23853924/2779fe76-07ef-11e7-9803-acfe0da90d1b.png)

any suggestions?

**Comment by ghost** [comment]
@mik115 reboot, replug the kb.

**Comment by mik115** [comment]
@light2yellow already done multiple times, nope.

**Comment by ghost** [comment]
@mik115 then execute this script https://github.com/mattanger/ckb-next/blob/cmake/macos/uninstall.sh to be sure that every instance (and even the old one) is dead and recompile the ckb-next (one last time, I promise) from `testing` (for example, it should work :) ). 

In case the kb is still not showing, execute:
```sh
sudo launchctl unload /Library/LaunchDaemons/com.ckb.daemon.plist
sudo /usr/bin/ckb-daemon
```
and provide the output.

You can also try the second option first, if you feel confident about what you've already tried.

**Comment by mik115** [comment]
Now it works! thx!

**Comment by ghost** [comment]
@mik115 

![74c](https://cloud.githubusercontent.com/assets/10786469/23857553/02e0b30c-07fe-11e7-8f5d-cee66976172c.jpg)

**Comment by mik115** [comment]
**You truly are the wisest wizard cat** 🤣  🤣
