### ISSUE TITLE
Strafe RGB sidelightToggled issue

### ISSUE THREAD

**Issue by jp94** [mattanger/ckb-next#107]
On ckb start, sidelight is on regardless of user settings. This also overrides 0% brightness setting.
If sidelight is toggled on while brightness is at 0%, interacting with GUI to toggle on/off sidelight will not work until brightness is adjusted above 0%.

I've tested on master and testing branch. This issue existed since /ckb branch, but I didn't bother to bring it up until now.

**Comment by tatokis** [comment]
CC @light2yellow 
Any ideas?

**Comment by ghost** [comment]
> On ckb start, sidelight is on regardless of user settings.

I can confirm this.

> This also overrides 0% brightness setting. If sidelight is toggled on while brightness is at 0%, interacting with GUI to toggle on/off sidelight will not work until brightness is adjusted above 0%.

I can confirm this too.

Thank you for reporting this.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/8
