### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by ghost** [mattanger/ckb-next#110]
Below is my vision on how an issue template should look like.

----

Switch on the "Preview" mode for better experience.

---

# You are supposed to:

- [ ] __Read__ the [`README.md`](https://github.com/mattanger/ckb-next/blob/master/README.md).
- [ ] __Skim__ through the other `.md` documents. The chances are they contain [at least] a mention of your problem or [at most] a solution to it.
- [ ] __Search__ before submitting an issue. The chances you will find [at least] a mention of your problem or [at most] a solution to it.
- [ ] __Avoid__ opening a new issue in case a similar one already exists (don't worry, we get the notifications for closed issues as well, it will be reopened if needed).
- [ ] __Keep__ unrelated issues separately (create a new one for a new problem).
- [ ] __Use__ Markdown to write on the GitHub. [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). Use triple backticks if copy-pasting more than _one_ line.

---

# A feature request?

- [ ] yes
- [ ] no

If __yes__, then:

### Any other notes & comments?

---

# A new device support request?

- [ ] yes
- [ ] no

If __yes__, then for
- [ ] __Linux__: upload the output of `ckb-dev-detect` shell script located at the root of the ckb-next source tree
- [ ] __macOS__: upload a full dump following the instructions [here](https://github.com/mattanger/ckb-next/issues/31#issuecomment-285380447)

---

# A bug report?

- [ ] yes
- [ ] no

If __yes__, then for

- [ ] __Linux__: 
* distribution's _name_:
* _version_ (pass if rolling):
* _output_ of `uname -r`:

- [ ] __macOS__:
* _version_:

#### Whence?
(how and where did you get this program, e.g.: _"`ckb-next-git` package in AUR"_ or _"built manually using quickinstall script"_ or _"pkg for macOS"_)

#### Version
(ckb-next's version which can be found in the "Settings" tab in the GUI, e.g.: _"ckb-next beta-v0.2.7"_)

#### Branch
(fill in if ckb-next was compiled manually, e.g.: _"master"_ or _"testing"_)

#### Logs & crash reports
(any useful information - an OS crash report, debugger's backtrace etc.)

In case of a crash you should at least provide a journal log gathered by your init system. Look for __usb__, __ckb__, __ckb-daemon__ and provide a meaningful context.

### Any other notes & comments?

---

# Something else?

---

Now what are _your_ observations on the above? Propose your changes and/or directly edit this message.

**Comment by ghost** [comment]
Rationale behind creation of a template can be found in #75.

**Comment by fleischie** [comment]
Although I feel this issue template is thorough, it also might be too extensive for the larger part of our audience. I fear that most people will remove all the text and still enter the most vague description of the problem.

I wonder, whether we can engage the more casual users with having checkboxes for the prerequisites. Perhaps with a disclaimer of retain the right to close issues uncommented, if we find the issue not suitable enough.

Also I would suggest we use international english (i.e. "behavior of the program" instead of "behaviour of the programme").

**Comment by ghost** [comment]
@fleischie rewritten.

**Comment by ghost** [comment]
Some of these ideas [from here](https://dev.to/danmademe/github-issues-helping-without-committing) may be incorporated into the above, one day.

**Comment by frickler24** [comment]
The idea is ok IMHO and will save our time. Two questions: 
1. How is this template working - do I get it as form when I click on "new issue"? 
2. And is it possible to have a short menu to select different forms? If yes, I think we could have two forms: One for feature request, one for bug-report/Question/other-issue.

Anyway: Let's start with it.

**Comment by ghost** [comment]
@frickler24 
It works [like that](https://github.com/blog/2111-issue-and-pull-request-templates), e. g. when user creates a new issue he gets it pre-filled with this template, that's all. Pretty straightforward, even too much. I'd be glad to see a more interactive process like choosing the template when creating an issue, but there's no such feature right now, so there's that.

**Comment by ghost** [comment]
The template above is obsolete now, track the changes on #133.
