### ISSUE TITLE
K65 RGB RAPIDFIRE problem with (SHIFT|COMMAND|OPTION)+mouse click

### ISSUE THREAD

**Issue by mrgaolei** [mattanger/ckb-next#112]
Every thing seems OK,

But, when I press shift + click(I want to select multi-line text), it doesn't selected.

And also, I press cmd + click in Safari (I want open link in new tab), it doesn't open.

In MacBook Pro's keyboard, it can be.

**Comment by ghost** [comment]
Duplicate of #29.
