### ISSUE TITLE
M65 Corsair Mouse ISSUE!!!!

### ISSUE THREAD

**Issue by JMONEYTX** [mattanger/ckb-next#120]
The mouse worked fine before i got this software. Now when i click and drag, the cursor shoots up to the top left and i cant do anything. PLEASE HELP!!

**Comment by ghost** [comment]
Merged into #93.

**Comment by AlfaceVerde** [comment]
Someone know how to solve this? I having the same problem with my Corsair Sabre RGB, tnks!
