### ISSUE TITLE
GUI Gets Cut Off

### ISSUE THREAD

**Issue by sam-gurdus** [mattanger/ckb-next#124]
Pretty self-explanatory. I am using macOS Sierra and the Strafe RGB.
![scr1](https://i.imgur.com/ZxrbsDh.jpg)
![scr2](https://i.imgur.com/SouYrhF.png)

**Comment by ghost** [comment]
Yep, this happens on Linux as well.

![screenshot_20170327_115651](https://cloud.githubusercontent.com/assets/10786469/24351084/bf266840-12e4-11e7-81cb-3f49beb54d3a.png)

**Comment by tatokis** [comment]
Looks like a Qt scaling issue, not sure what can be done about it.
![633cff16a285](https://cloud.githubusercontent.com/assets/6003656/24550625/9b6255ae-1627-11e7-8cd2-ab770b7188d4.jpg)

**Comment by frickler24** [comment]
@samrocks9 and @light2yellow Do you have scaling factors active? On my mint with 100% scale factor it looks fine as it does at @tatokis screenshot

**Comment by tatokis** [comment]
@frickler24  I am positive @light2yellow has scaling enabled.

**Comment by ghost** [comment]
@frickler24, @tatokis yes, you are right. I use 4k monitor and an NVIDIA video card, so I installed a proprietary NVIDIA driver and now `xdpyinfo` reports 184x182 dpi. I also use KDE Plasma and SDDM, they both have out-of-box HiDPI support.

Looking at other Qt applications I use ( Viber, Telegram), they "solved" this by providing an interface size slider. 

![screenshot_20170401_154910](https://cloud.githubusercontent.com/assets/10786469/24579304/d546dbc0-16f2-11e7-8ef0-530a799a46d7.png)


Either it was done at the period of time when Qt's HiDPI support was poor, or it's still poor (at least by default), but why then Plasma and SDDM, both heavily relying on Qt, have such a great HiDPI support?

**Comment by sam-gurdus** [comment]
I don't think I have any scaling on. I'm just using an iMac without a second monitor.

**Comment by frickler24** [comment]
hmmm, seems that we have two different bugs in the ui definition:
@light2yellow you can see, that the keyboard-buttons are scaled down.
But in the picture from @samrocks9 we have just the buttons moved downwards.
When I added the macro tab, I had several problems bringing all UI elements in the tab. Resizing is ignored by qt.
Is there anybody with high experience in qt UI definitons?

**Comment by tatokis** [comment]
@frickler24 , @light2yellow has pointed this out. 
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/application.cpp#L634

Perharps we can do something similar?

**Comment by ghost** [comment]
@frickler24 well, I experience both :)
If I switch to the Macro tab (which I should've done before but instead made a screenshot of the Program), then it all becomes a total mess with unreachable buttons below.

![screenshot_20170402_163305](https://cloud.githubusercontent.com/assets/10786469/24588104/5d3129e4-17c2-11e7-85f3-40e5d1d8234f.png)

Regarding Telegram, the way they implement macros from the link posted above is unclear to me, they play with the preprocessor [here](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/settings.h#L40) to create c* function calls.

Anyway, it looks more like there's a hardcoded height somewhere, where it shouldn't be.

**Comment by tatokis** [comment]
@light2yellow This should be it https://github.com/mattanger/ckb-next/blob/master/src/ckb/kbbindwidget.ui#L206-L210

**Comment by tatokis** [comment]
also, vsize is fixed. https://github.com/mattanger/ckb-next/blob/master/src/ckb/kbbindwidget.ui#L195

**Comment by mst3kharris** [comment]
Hello, I've just installed this driver for my Corsair M65 mouse.  It appears to be working beautifully; however, the GUI for the settings is too tall for my screen.  I'm running an old-ish Dell laptop and the screen resolution is fixed at 1366x768.  I'm able to change the size of the GUI horizontally, but not vertically, which is to be expected if vsize has a fixed value.  Attached is a screenshot of my workspace, where you can see the bottom of the window cuts off the buttons for saving settings, applying them, et cetera.
![ckb-gui-issue](https://cloud.githubusercontent.com/assets/27095998/24832632/315f3584-1c79-11e7-879f-fcbe12e8a5a8.png)

**Comment by ghost** [comment]
@mst3kharris thanks for reporting back, I'll try to do something else to it.

**Comment by ghost** [comment]
@mst3kharris did you actually try the PR mentioned above and get such results or are you posting the issue about current GUI in `master` or `testing` just because this thread mentions GUI?

**Comment by ghost** [comment]
Regardless, I've just tested our `master` on 1366x768 and it indeed doesn't even fit into the screen. I'll take a look at it.

**Comment by ghost** [comment]
Sorry, I'm not able to fix this. It requires a redesign and I neither know all the widgets and frames, nor I know how to write GUI applications in Qt.

You can find my pathetic attempts under `dehardcoded-gui` branch, but I recommend starting from scratch.

**Comment by sam-gurdus** [comment]
I have reinstalled ckb after months of going without it, but am still having this issue. It is preventing me from making macros. Any progress or workarounds?

**Comment by Ravenslofty** [comment]
Short of rewriting the GUI, no, not really.

**Comment by sam-gurdus** [comment]
Hmm. It seems like an important thing to be fixed, considering it cuts off
crucial parts of the program. I have no way of setting macros and stuff.
Why can't the window just be scrolled?

**Comment by Ravenslofty** [comment]
The GUI was written by somebody who knew Qt well enough to create a very functional interface with it. But nobody on the current development team knows much Qt at all, so we don't know what to do.

**Comment by ghost** [comment]
There's a PR that provides scrolling, but its scrolling is deficient because it adds additional widget or something. Then, @tatokis did some job and implemented a proper scroll, but never published it. I request @tatokis's response for comment on their work (I am satisfied with it).

**Comment by fdagpigj** [comment]
If nobody knows Qt well enough to fix the GUI, why not add a command-line interface?

**Comment by fleischie** [comment]
@fdagpigj we actually had at some point, maybe even do.... You can eve  try to talk to the server directly and store the settings in a local file or something.

Anyway this is not really the point of this issue. So thanks for your concern and happy holidays. 🎉

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/11
