### ISSUE TITLE
I am unable to use the launch program function with programs that have a space in their name

### ISSUE THREAD

**Issue by sam-gurdus** [mattanger/ckb-next#125]

**Comment by sam-gurdus** [comment]
I have found a workaround. All you do is add a ' before the file path and one at the very end. https://i.imgur.com/j37JH4p.png

**Comment by ghost** [comment]
May I ask, how is this related to ckb-next?

**Comment by ghost** [comment]
Ah, I see now, Binding -> any active key -> Program.

Thank you for providing a workaround, we'll add it to the README.

**Comment by tatokis** [comment]
I wouldn't really call this an issue, but good to see you figured it out.

**Comment by ghost** [comment]
Oh, actually it's just a regular shell command, I didn't get it for the first time. Thus as it is a common shell syntax, we won't change the README.
