### ISSUE TITLE
Modes Disappeared 

### ISSUE THREAD

**Issue by sam-gurdus** [mattanger/ckb-next#128]
When I rebooted/crashed my computer I lost all of my modes in ckb. These had some pretty awesome animations/colors and all my bindings. I was wondering if not a fix, is there was any way I could recover them. I am using macOS Sierra

**Comment by ghost** [comment]
Try #90.

**Comment by sam-gurdus** [comment]
How would I go about installing this 'patch?'

**Comment by ghost** [comment]
As with https://github.com/mattanger/ckb-next/issues/29#issuecomment-289412693.

**Comment by tatokis** [comment]
Closing as duplicate of #83.
