### ISSUE TITLE
[OS X] quickinstall script doesnt include ckb-daemon?

### ISSUE THREAD

**Issue by syropian** [mattanger/ckb-next#134]
After cloning master into my home folder, I simply cd'd in and ran the quickinstall script. It built the app, and I booted it up but I noticed it wasn't detecting my keyboard. I checked Activity Monitor and noticed `ckb.app` was running but not `ckb-daemon`, which explained my keyboard not being detected. I figured I could just manually start the daemon but a peek inside `ckb.app/Contents/Resources` revealed that the daemon wasn't even present. Is this where it's supposed to be, or does it live somewhere else?  If there's any logs or files I can include to help let me know.

**Comment by ghost** [comment]
Yes, please. Send us everything that was produced by `./quickinstall` (including your decisions (Y/n)). Just copy-paste from the terminal.

**Comment by syropian** [comment]
the quickinstall script never prompted me for any y/n answers. It spit out a ton of warnings, mostly about unused parameters and such. However this one stuck out:
```
1 warning generated.
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _u16enc in profile.o
      _u16dec in profile.o
  "_libiconv_open", referenced from:
      _u16enc in profile.o
      _u16dec in profile.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../../ckb.app/Contents/Resources/ckb-daemon] Error 1
make[1]: *** [debug] Error 2
make: *** [sub-src-ckb-daemon-make_first] Error 2
make: *** Waiting for unfinished jobs....
```

If you really want me to paste the entire output i can but its about a mile long.

Also, if it helps I'm on macOS Sierra 10.12.1

**Comment by ghost** [comment]
Do `xcode-select --install` and try again.

**Comment by syropian** [comment]
@light2yellow I had the cli tools installed already, but I wasn't fully up to date. Updated them, did a restart and ran quickinstall again but unfortunately same error.

**Comment by ghost** [comment]
Alright. Then do `./quickinstall > out.txt` and upload the text file.

**Comment by ghost** [comment]
Also, do you have XCode installed?

**Comment by syropian** [comment]
I do have XCode installed but its also not fully up to date. Let me get that all updated and I'll try again. If that fails I'll upload the output text.

**Comment by syropian** [comment]
@light2yellow Hm, still no dice. I updated XCode and also updated my OS to 10.12.4. Here's the output - [out.txt](https://github.com/mattanger/ckb-next/files/891430/out.txt)

**Comment by syropian** [comment]
If I were to guess, I'd say whatever is trying to use libiconv likely just has the wrong path. `which iconv` points me to `/usr/bin`. I'm not sure how to check where the installer is specifically looking though.

**Comment by ghost** [comment]
@syropian I think I know what's the problem, working on it.

**Comment by ghost** [comment]
Please, try compiling from `testing` now. I pushed a commit, so you'll need to `pull` or redownload a single branch (like here https://github.com/mattanger/ckb-next/issues/29#issuecomment-289412693, but make sure you're not inside a git repo if you decide to download).

This should fix all issues.

**Comment by syropian** [comment]
Did you push to `testing`? Github says last commit was Jan 22nd

**Comment by ghost** [comment]
Yes, exactly :)
GitHub lied to you :)

**Comment by syropian** [comment]
Oh! Thought you meant you _just_ pushed, my bad! 😅

**Comment by syropian** [comment]
That seems to work, thanks! Will those changes make to master any time soon?

**Comment by ghost** [comment]
Yes, I'll merge them right now. Just wanted to be sure nothing will break.

**Comment by ghost** [comment]
Done. Now you can use `master` too.

This was an old issue that was fixed long time ago but didn't make into any of the branches because I was the only one experiencing these problems.
