### ISSUE TITLE
K70 LUX RGB

### ISSUE THREAD

**Issue by datasmurfen** [mattanger/ckb-next#136]
K70 LUX RGB not detected in Arch based Linux (Antergos).

**Comment by ghost** [comment]
Install an AUR package.

**Comment by datasmurfen** [comment]
Allready done that...

**Comment by datasmurfen** [comment]
But it doesn't help..

**Comment by ghost** [comment]
Do `systemctl start ckb-daemon`.

**Comment by datasmurfen** [comment]
Thanks. That worked :100: :+1:

**Comment by ghost** [comment]
Please, read the post-transaction information next time.

![screenshot_20170405_001902](https://cloud.githubusercontent.com/assets/10786469/24681442/859c2896-1995-11e7-8d50-07078c18b22a.png)
