### ISSUE TITLE
K95 RGB Platinum Detection issue

### ISSUE THREAD

**Issue by ConnorGavitt** [mattanger/ckb-next#137]
[ckb-dev-detect-report.gz](https://github.com/mattanger/ckb-next/files/901449/ckb-dev-detect-report.gz)
The settings panel shows the keyboard as not being connected and thus makes it impossible to configure.

**Comment by ghost** [comment]
Thanks for sending the report. There's one already in #2. Try running what @tatokis offers in #53 and respond there.
Merged into #53.
