### ISSUE TITLE
Drop the "forked from"

### ISSUE THREAD

**Issue by chicks-net** [mattanger/ckb-next#14]
If you guys want to get full credit in github's system for your commits** to this project you need to tell them to disassociate you from the project you forked from. Since you've renamed the project it is probably a good time to do this.  http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository explains it in a bit more detail, but all you have to do is get in touch with github support and they'll take care of this for you in a few days.  Putting in a link to the "old" project and asking for them to link to you would seem fair, but just getting the "forked from" killed off is all I'm asking for in this issue.

** commits to a fork don't show up in your personal profile graphs until they're accepted by the parent of the fork.

**Comment by mattanger** [comment]
Cool, hadn't realized that was happening. Thanks for the heads up!
