### ISSUE TITLE
Incorrect key mapping in mviz

### ISSUE THREAD

**Issue by pseudoArchaea** [mattanger/ckb-next#143]
Using the latest git build - the music visualizer isn't working. I can see in pavucontrol that the fallback device does have sound coming out of it(I can hear that after all), but the keys are all white.

I tried using the default animation settings and I tried messing with them too to no avail.

Is this not supposed to be working yet or am I doing something incorrectly?

**Comment by tatokis** [comment]
The mviz plugin is a bit of a mess at the moment, it seems that the key mapping is off. (Patches are welcome.)

First set a solid background colour, add the mviz plugin, open up pavucontrol and make sure it is recording from the monitor device.
This should be enough to get something to show.

You can then open the settings menu for the animation, and open the "Fade color" prompt.
Try setting a colour on the far right.

**Comment by pseudoArchaea** [comment]
Actually now I can't see the mviz plugin at all. I can see it's somehow related to the pulse libraries, which I don't recall removing.

  pacman -Q | grep pulse
lib32-libpulse 10.0-1
libcanberra-pulse 0.30-8
libpulse 10.0-2
pulseaudio 10.0-2
pulseaudio-alsa 2-3
pulseaudio-gconf 10.0-2

**Comment by tatokis** [comment]
Run `ckb` in a terminal and see if it finds it there, if not, try reinstalling.

It just depends on libpulse and libpulse-simple, so be sure to have both installed, otherwise it won't get compiled.

**Comment by ghost** [comment]
@tatokis libpulse-simple is the part of libpulse on Arch (just for the information):
```
$ pkgfile libpulse-simple.so
extra/libpulse
community/libpulse-nosystemd
multilib/lib32-libpulse
```

**Comment by pseudoArchaea** [comment]
Recompiled against the new git version, now the plugin is there again.


>First set a solid background colour, add the mviz plugin, open up pavucontrol and make sure it is recording from the monitor device.
>This should be enough to get something to show.

Yup, that did it. Had to set it in pavucontrol.

The mapping does seem off, for some reason the 3 keys on the far right on the numpad act as if they were way closer to the left.

Also the way the visualizer works right now(from left to right) makes right half of the keyboard almost always untouched by the visualizer. Would prefer it to be from bottom to top.

Great work so far!

**Comment by ghost** [comment]
> the 3 keys on the far right on the numpad act as if they were way closer to the left

Could you elaborate on what are those keys? Every key has a mark/tag/picture on it after all :)

What keyboard do you use?

**Comment by tatokis** [comment]
The - + and enter keys all the way to the right.
I can reproduce this too

**Comment by nonchip** [comment]
also I'd like to note there's always one key "stuck" at 100%.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/13
