### ISSUE TITLE
"No Devices Connected" Please Help

### ISSUE THREAD

**Issue by DesperateKidNeedsHelp** [mattanger/ckb-next#150]
I tried many different solutions for CKB to work so I can change my keyboard's ugly color. Please can anyone help me?

**Comment by JarrenJ** [comment]
Could you be more specific what exactly is the problem... what isn't connecting? Did you trying restarting your computer? What version are you using. Are you running MacOS or Linux? Please add more details so we can pinpoint your problem.

--**thx**

**Comment by DesperateKidNeedsHelp** [comment]
I tried restarting my computer and unplugging the cords. I am running MacOS Sierra. My keyboard works just fine but I just want this color to be changed and maybe an animation to go along. I have the K70 RGB which is one of the keyboards that is supported by CKB. @JarrenJ

**Comment by tatokis** [comment]
How did you install ckb?

**Comment by DesperateKidNeedsHelp** [comment]
I downloaded it as binary @tatokis

**Comment by DesperateKidNeedsHelp** [comment]
Oops..

**Comment by tatokis** [comment]
The binaries are ridiculously updated, you have to compile from source. 
There's plenty of info in the readme on how to do it.

**Comment by DesperateKidNeedsHelp** [comment]
So I have to download XCode and Qt5 to compile it? @tatokis

**Comment by ghost** [comment]
Yes, and while you're waiting for the software to download, find 10 minutes to read the README.

**Comment by DesperateKidNeedsHelp** [comment]
Ok, everything is downloaded, but.. What's up with the scripts how do I use them??? I noticed that you can do script stuff in Qt5. Please help these are my last steps.. @tatokis

**Comment by frickler24** [comment]
@DesperateKidNeedsHelp Your question is answered in the READE.md. PLease follow @light2yellow's hint and **read it**.

**Comment by DesperateKidNeedsHelp** [comment]
Ok. @frickler24

**Comment by DesperateKidNeedsHelp** [comment]
Well I read everything, but I already read it before.

**Comment by tatokis** [comment]
https://github.com/mattanger/ckb-next#building-from-source

> The easiest way to build the driver is with the quickinstall script, which is present in the ckb-master folder. Double-click on quickinstall and it will compile the app for you, then ask if you'd like to install it system-wide.

**Comment by DesperateKidNeedsHelp** [comment]
Yes I read that a lot of times, but where do I double click it.. Do I need to download GitHub Desktop? (I already have it downloaded) I'm so confused.. @tatokis

**Comment by ghost** [comment]
https://stackoverflow.com/questions/6466945/fastest-way-to-download-a-github-project
Second result for "how to download from github" request.

**Comment by DesperateKidNeedsHelp** [comment]
Ok, I remember downloading this not knowing what I was doing. I just don't know how to make the code actually.. work. (Or am I supposed to use that HTML or SSH thing) @light2yellow

**Comment by ghost** [comment]
To make the code actually work, you first read the link from my last message, then you read the README and then execute just 3 commands - cloning, cd'ing and quickinstall'ing.
