### ISSUE TITLE
Issue with Japanese input source and caps lock

### ISSUE THREAD

**Issue by lilac-eclipse** [mattanger/ckb-next#151]
I have an issue with the Japanese input source on macOS Sierra. I have caps lock off for "Romaji" input enabled, such that turning caps lock on allows me to type in Japanese, while turning it off allows me to type in English. This software makes it so I can activate Japanese mode, but can't disable it once I press the caps lock.
![image](https://cloud.githubusercontent.com/assets/3729013/24937333/9ca9ff4e-1ef5-11e7-9fd0-733457a48b5b.png)

**Comment by ghost** [comment]
Although I have no experience with mapping Caps to switch languages, you should be aware of some serious issues with it (#23) leading to a fully unusable desktop up to hard reboot.
