### ISSUE TITLE
Caps Lock won't unlock

### ISSUE THREAD

**Issue by lilac-eclipse** [mattanger/ckb-next#158]
MacOS Sierra v10.12.4

Hitting Caps Lock on Lux K70 RGB turns on caps lock. The keyboard light on the K70 and on the mac keyboard both turn on. Pressing caps lock further won't turn caps lock off however.

**Comment by lilac-eclipse** [comment]
Related to #151

**Comment by ghost** [comment]
Do you experience freezes like in #23?

**Comment by lilac-eclipse** [comment]
Doesn't seem to be. I've experienced no crashes. Similarly, changing the caps lock mode didn't solve the issue.

**Comment by ghost** [comment]
Hmm. Okay. So the Caps Lock issue doesn't happen to everyone.

Anyway, we again have issues with modifiers state not being recorded or vanished or changed when not expected.

CC
@auibrian

**Comment by ghost** [comment]
Maybe we're able to add a good amount of debugging messages for @Cryocubed to post the logs? (And have @frickler24's work on debug levels merged)

**Comment by lilac-eclipse** [comment]
I can post whatever, just let me know what you need/how to get it.

**Comment by lilac-eclipse** [comment]
Unsure of what changed, but the problem has fixed itself.

**Comment by Donzap** [comment]
I have the exact same problem, when I hit Caps on my K65 RGB it write cap letters, but i press it again and it didn't unlock, if I want to unlock caps I must press caps on laptop's keyboard (I use it on a macbook pro).

Any idea or clue on what you did?
