### ISSUE TITLE
newfx branch problem

### ISSUE THREAD

**Issue by sh4d0w28** [mattanger/ckb-next#16]
right now i have problem with building newfx branch on Ubuntu 16.04 (problem with pusleaudio library). Is it possible to have a complete manual how to build it?

Thanks.

**Comment by mattanger** [comment]
Hi, @sh4d0w28 aside from what's already in the documentation we don't, and it may be a little while before we have any more information. Right now, we're not really offering any support at all. But, if you'd like to report an bug/problem, (which you may have), please provide a more detailed list of any errors that you've encountered.
