### ISSUE TITLE
"No devices connected" error, no lighting

### ISSUE THREAD

**Issue by stellarsarah** [mattanger/ckb-next#161]
I just got a K70 RGB Rapidfire. First thing I did was plug into a windows computer and used CUE to update firmware (CUE says it's running 2.05). I also fiddled around a bit with some of the presets available in CUE and saved one to device memory, in case that's relevant. I then installed ckb on my mac and plugged in the keyboard. 

So far, still unable to get the RGB lights to work at all on either of my macs, both running 10.9.5. Ckb just says "No devices connected". Keyboard input registers fine--even the music control buttons are communicating with iTunes with no hassle. Just zero lighting. 

I've tried a bunch of different combinations of toggling the poll rate switch, restarting computers, uninstalling and reinstalling ckb, and switching up which USB ports I use. I don't have a hub handy so I haven't tried that. And while troubleshooting, I saw the linked forum post about USB connection requirements and have since been plugging in the connector with the two arrows icon before the one with the keyboard icon each time. Still nothing.

Sorry for any extraneous info. Let me know if you have any suggestions or want any further info. Thank you for reading.

**Comment by tatokis** [comment]
Compile from source

**Comment by stellarsarah** [comment]
It's working now, thanks.

**Comment by hypendex** [comment]
What does compile from source mean?

**Comment by ghost** [comment]
@hypendex 

It means that instead of using a macOS pkg (and I suppose from the word "iTunes" @stellarsarah is/was using macOS) you follow the README instructions.

But you'd better google it anyway.

Also, if you have a recent version of Qt (like 5.9) then you'll get compilation errors that we don't know how to fix yet.
