### ISSUE TITLE
Support for new keyboard K63

### ISSUE THREAD

**Issue by tonyfreelance** [mattanger/ckb-next#162]
Hi guys,

Firstly thanks for this awesome driver. Recently I just got a new K63 which seems not supported yet. I would highly appreciate if anyone can support this one. I'm using it on MacOS 10.12.4

Thanks :)

**Comment by tatokis** [comment]
Please run the ckb-dev-detect script located in the root of the repository.

**Comment by tonyfreelance** [comment]
I did run it. And after it said: "This script will collect information about the Corsair devices in your system.Please make sure they are plugged in and press Enter.", I hit Enter and my iTerm screen disappeared so quicky that I didn't notice what happened..

**Comment by tatokis** [comment]
Did it generate a report file?
Try opening a terminal manually, and then run
```
cd path/to/ckb-next/
./ckb-dev-detect
```

That should tell you what went wrong

**Comment by tonyfreelance** [comment]
Hey, it works now!

Here is what I got after following your instruction:
`ckb-dev-detect - Tue Apr 25 21:00:40 +07 2017

Kernel: Darwin tony 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

OS Version:
ProductName:    Mac OS X
ProductVersion: 10.12.4
BuildVersion:   16E195

USB Devices:
        Corsair Gaming K63 Keyboard:

          Product ID: 0x1b40
          Vendor ID: 0x1b1c  (CORSAIR MEMORY INC.)
          Version: 1.00
          Serial Number: 02028039AEC9810456AD84DCF5001947
          Speed: Up to 12 Mb/sec
          Manufacturer: Corsair
          Location ID: 0x14100000 / 3
          Current Available (mA): 500
          Current Required (mA): 500
          Extra Operating Current (mA): 0`

Thanks :)

**Comment by ghost** [comment]
Linking this to #2.

**Comment by Segflow** [comment]
Any update?

**Comment by ghost** [comment]
@Segflow 
None.

You can start implementing this if you would like to, it seems to be a subset of other keyboard models, so it needs only choosing from and reducing the amount of existing features for other, more feature-complete keyboards.

**Comment by tatokis** [comment]
As a quick solution that might just work, try editing usb.h and adding your keyboard as K65_NRGB.

Try the following patch and see what happens.
```
diff --git a/src/ckb-daemon/usb.h b/src/ckb-daemon/usb.h
index d2a577b..3f37d59 100644
--- a/src/ckb-daemon/usb.h
+++ b/src/ckb-daemon/usb.h
@@ -40,8 +40,8 @@
 
 #define P_K65           0x1b17
 #define P_K65_STR       "1b17"
-#define P_K65_NRGB      0x1b07
-#define P_K65_NRGB_STR  "1b07"
+#define P_K65_NRGB      0x1b40
+#define P_K65_NRGB_STR  "1b40"
 #define P_K65_LUX       0x1b37
 #define P_K65_LUX_STR   "1b37"
 #define P_K65_RFIRE     0x1b39
```

**Comment by tatokis** [comment]
CC @Segflow

**Comment by Segflow** [comment]
@tatokis 
Same.

**Comment by tatokis** [comment]
@Segflow what happens if you stop ckb-daemon and run it manually from a terminal?

**Comment by Segflow** [comment]
Actually after `sudo systemctl start ckb-daemon` the keyboard stop working. (nothing happens when i type something)

**Comment by Segflow** [comment]
Even with manual start:
```
 ~/ckb-next/bin   master ●  sudo ckb-daemon 
    ckb: Corsair RGB driver v0.2.8
[I] Root controller ready at /dev/input/ckb0
[I] Connecting Corsair Gaming K63 Keyboard at /dev/input/ckb1
[I] Starting input thread for /dev/input/ckb1
[I] Setup finished for /dev/input/ckb1



```

**Comment by tatokis** [comment]
Try this 
```
diff --git a/src/ckb-daemon/usb.h b/src/ckb-daemon/usb.h
index d2a577b..8ddbbdb 100644
--- a/src/ckb-daemon/usb.h
+++ b/src/ckb-daemon/usb.h
@@ -38,6 +38,9 @@
 #define V_CORSAIR       0x1b1c
 #define V_CORSAIR_STR   "1b1c"
 
+#define P_K63           0x1b40
+#define P_K63_STR       "1b40"
+
 #define P_K65           0x1b17
 #define P_K65_STR       "1b17"
 #define P_K65_NRGB      0x1b07
@@ -46,7 +49,7 @@
 #define P_K65_LUX_STR   "1b37"
 #define P_K65_RFIRE     0x1b39
 #define P_K65_RFIRE_STR "1b39"
-#define IS_K65(kb)      ((kb)->vendor == V_CORSAIR && ((kb)->product == P_K65 || (kb)->product == P_K65_NRGB || (kb)->product == P_K65_LUX || (kb)->product == P_K65_RFIRE))
+#define IS_K65(kb)      ((kb)->vendor == V_CORSAIR && ((kb)->product == P_K65 || (kb)->product == P_K65_NRGB || (kb)->product == P_K65_LUX || (kb)->product == P_K65_RFIRE || (kb)->product == P_K63))
 
 #define P_K70                0x1b13
 #define P_K70_STR            "1b13"
@@ -122,7 +125,7 @@ const char* product_str(short product);
 /// The difference between non RGB and monochrome is, that monochrome has lights, but just in one color.
 /// nonRGB has no lights.
 /// Change this if new \b monochrome devices are added
-#define IS_MONOCHROME(vendor, product)  ((vendor) == (V_CORSAIR) && (product) == (P_STRAFE_NRGB))
+#define IS_MONOCHROME(vendor, product)  ((vendor) == (V_CORSAIR) && ((product) == (P_STRAFE_NRGB) || (product) == (P_K63)))
 
 /// For calling with a usbdevice*, vendor and product are extracted and IS_RGB() is returned.
 #define IS_RGB_DEV(kb)                  IS_RGB((kb)->vendor, (kb)->product)
```

**Comment by Segflow** [comment]
Now the ckb tool detect a device with the name k63 but:
- Keyboard not working (no response from any key)
- nothing happen when i interact with ckb (set lighting mode etc..)

i close the deamon and i can type again using the keyboard

```
    ckb: Corsair RGB driver v0.2.8
[I] Root controller ready at /dev/input/ckb0
[I] Connecting Corsair Gaming K63 Keyboard at /dev/input/ckb1
[I] Starting input thread for /dev/input/ckb1
[I] Setup finished for /dev/input/ckb1

```

**Comment by tatokis** [comment]
Looks like I never posted about this in here, @tonyfreelance other than a few media keys, the rest should be working with code from this branch.
https://github.com/mattanger/ckb-next/tree/newdev

**Comment by sonikbhoom** [comment]
@tatokis I used the src.rpm from johanh and added your patch to the spec file, rebuilt the RPM and installed.  I can use the keyboard (as before: with ckb-next-0.2.8-0.6.20170820git6af2773), but it does not get its own tab in the qt gui, as I suspect from the attached report it is not detected.  

```
Aug 27 18:14:41.980588 darkdog3 kernel: usb 1-1.3: New USB device found, idVendor=1b1c, idProduct=1b40
Aug 27 18:14:41.980659 darkdog3 kernel: usb 1-1.3: Product: Corsair Gaming K63 Keyboard
Aug 27 18:14:41.980694 darkdog3 kernel: usb 1-1.3: Manufacturer: Corsair
Aug 27 18:14:41.981034 darkdog3 kernel: input: Corsair Corsair Gaming K63 Keyboard as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.3/1-1.3:1.0/input/input2
Aug 27 18:14:41.981446 darkdog3 kernel: usb 1-1.4: New USB device found, idVendor=1b1c, idProduct=1b2f
Aug 27 18:14:41.981517 darkdog3 kernel: usb 1-1.4: Product: Corsair Gaming SABRE RGB Mouse
Aug 27 18:14:41.981552 darkdog3 kernel: usb 1-1.4: Manufacturer: Corsair
Aug 27 18:14:41.981600 darkdog3 kernel: input: Corsair Corsair Gaming SABRE RGB Mouse as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.4/1-1.4:1.0/input/input3
```

but no device in daemon:

```
18:19:45 [root@darkdog3 ckb-daemon]# systemctl status ckb-daemon -l 
● ckb-daemon.service - Corsair Keyboard Daemon
   Loaded: loaded (/usr/lib/systemd/system/ckb-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-08-27 18:14:58 EDT; 4min 58s ago
 Main PID: 1017 (ckb-daemon)
   CGroup: /system.slice/ckb-daemon.service
           └─1017 /usr/libexec/ckb-daemon

Aug 27 18:14:58 darkdog3 systemd[1]: Started Corsair Keyboard Daemon.
Aug 27 18:14:58 darkdog3 systemd[1]: Starting Corsair Keyboard Daemon...
Aug 27 18:14:58 darkdog3 ckb-daemon[1017]: ckb: Corsair RGB driver v0.2.8
Aug 27 18:14:58 darkdog3 ckb-daemon[1017]: [I] Root controller ready at /dev/input/ckb0
Aug 27 18:14:58 darkdog3 ckb-daemon[1017]: [I] >>>vendor = 0x1b1c, product = 0x1b2f, path = /dev/bus/usb/001/004, syspath = /sys/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.4
Aug 27 18:14:58 darkdog3 ckb-daemon[1017]: [I] Connecting Corsair Gaming SABRE RGB Mouse at /dev/input/ckb1
Aug 27 18:14:58 darkdog3 ckb-daemon[1017]: [I] claiming interfaces. name=Corsair Gaming SABRE RGB Mouse, firmware=0204; Got >> 3<< as ep_str
Aug 27 18:14:58 darkdog3 ckb-daemon[1017]: [I] claiming 3 endpoints
Aug 27 18:14:58 darkdog3 ckb-daemon[1017]: [I] Starting input thread for /dev/input/ckb1
Aug 27 18:15:01 darkdog3 ckb-daemon[1017]: [I] Setup finished for /dev/input/ckb1

```

[ckb-dev-detect-report.gz](https://github.com/mattanger/ckb-next/files/1254763/ckb-dev-detect-report.gz)

**Comment by tatokis** [comment]
@sonikbhoom that patch above was nowhere near enough what was needed to get this working.
The few issues I mentioned above remain, but I would suggest not using the package for now and compiling directly from newdev.

There have been a lot of changes in newdev, and I think it wouldn't be worth generating a patch and applying it manually.

**Comment by sonikbhoom** [comment]
I downloaded the newdev branch and applied it to the SPEC file from the other src.rpm, removing the patches.  (note: I like clean, removable, installs and rpms can be made to clean up after themselves)
The keyboard is detected and I'm running beta-0.2.8.

**Comment by sonikbhoom** [comment]
I downloaded the newdev branch and applied it to the SPEC file from the other src.rpm, removing the patches.  (note: I like clean, removable, installs and rpms can be made to clean up after themselves)
The keyboard is detected and I'm running beta-0.2.8. 

`edit: After rebooting, the mouse doesn't work at all.  I have reverted and will try again later.`

**Comment by tatokis** [comment]
K63 is now in master. If anyone is willing to help me map out some of the broken media keys, it would be appreciated.

**Comment by triyanarief** [comment]
ok, i just bought k63 and gonna try to install in sierra. hopefully it works.

**Comment by acwest** [comment]
I am working on adding the Strafe MX Silent right now (1B44), and have been unable to determine where the firmware files are downloaded from. It should be indistinguishable from the Strafe, but I don't want to risk trying to flash the wrong firmware. How do we normally determine where to download firmwares from?

**Comment by ghost** [comment]
@acwest we tip and try if it works. For some keyboards we weren't able to determine the addresses. However, the owner of the keyboard can always determine the address by monitoring the CUE application on Windows.

**Comment by tatokis** [comment]
Should be fully supported in https://github.com/ckb-next/ckb-next

**Comment by xipher1** [comment]
Not to dig up an old horse, but ;

> This script will collect information about the Corsair devices in your system.
> Please make sure they are plugged in and press Enter.
> 
> 2018-04-09 19:26:42.803 system_profiler[50325:8092645] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
> Done! Please send the following report to the developers.
> Location: [redacted]

and then

> $ cat ckb-next-dev-detect-report
> ckb-next-dev-detect - Mon Apr  9 16:09:36 HKT 2018
> 
> Kernel: Darwin blinky 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
> 
> OS Version:
> ProductName:	Mac OS X
> ProductVersion:	10.13.4
> BuildVersion:	17E199
> 
> USB Devices:
>                 CORSAIR K63 Wireless Mechanical Gaming Keyboard:
> 
>                   Product ID: 0x1b45
>                   Vendor ID: 0x1b1c  (CORSAIR MEMORY INC.)
>                   Version: 1.01
>                   Serial Number: 0202C023AF081CE7589194B3F5001BC7
>                   Speed: Up to 12 Mb/sec
>                   Manufacturer: CORSAIR
>                   Location ID: 0x14414000 / 32
>                   Current Available (mA): 500
>                   Current Required (mA): 500
>                   Extra Operating Current (mA): 0
> 
> Daemon log:
>     ckb-next: Corsair RGB driver 0.2.9-160-gf5802bf
> [I] Root controller ready at /var/run/ckb0
> [I] Registering EventTap for modifier keys.
> 
> GUI log:

This is obv in High Sierra, connected via USB, through a usb-c -> usb-a dongle. Keyboard works fine, but the GUI says that no device is connected.

**Comment by tatokis** [comment]
@xipher1 Your keyboard is a wireless one, which is not supported at the moment.
That aside, open an issue in ckb-next/ckb-next. Not here.

**Comment by xipher1** [comment]
oops, my bad, I had a bunch of tabs opened, thought I was left on the correct one. Sorry, I will do so in the morning! Thanks

**Comment by Ravenslofty** [comment]
Actually, ckb-next/ckb-next has an issue, which is my wireless branch; though I suspect we might need to add the K63 and Dark Core simultaneously because of how much common protocol there is between them.

**Comment by tatokis** [comment]
@ZirconiumX Indeed, but keep in mind, there are still differences such as the inability to control per key lighting (compared to per zone on the dark core).

**Comment by xipher1** [comment]
Thanks for the prompt replies guys, I'll take a look at the issue tmrw, happy to help test anything, very comfortable with everything involved.

**Comment by songliqiangcn** [comment]
I just bought a Corsair K63 Wireless Mechanical Gaming Keyboard. But looks it doesn't support Mac OS to select the light. Did search found this post. 
Does it support my Mac OS 10.13.6 ? 
Thanks,

**Comment by tatokis** [comment]
Not yet, sorry
