### ISSUE TITLE
macros and remapped keys

### ISSUE THREAD

**Issue by lstkz** [mattanger/ckb-next#164]
macOS 10.11

- Ctrl and Command keys are swapped.
- G9 is a simple macro: Command + Tab (`+lctrl,+tab,-tab,-lctrl`).

Steps:
a) I have two spaces and each space contains an instance of WebStorm IDE.
b) When I press `ctrl+~` it switches between WebStorm IDEs.
c) G9 (command + tab) should switch between tabs in a single IDE.

Bug:
When pressing c) the IDE windows are switches.
I think it invokes `ctrl+tab` and then `cmd+tab`. When I press G9 multiple times it starts working correctly.

Notes:
- It always works correctly if I press `cmd+tab` instead of G9.
- It occurs only with b) step.

**Comment by frickler24** [comment]
I have no macOS myself, so I speculate with my answer: Your first info is 
> Ctrl and Command keys are swapped.

Ckb daemon does not know anything about this.
So if your macro is` +lctrl, +tab, -tab, -lctrl` - is it possible for your macOS that it does interpret it as `+cmd, +tab, -tab, -cmd`? Did you try a macro with this "reverse" definition?

**Comment by lstkz** [comment]
No, the macro keys are correct.
My macro works correctly, but if I make b) step the behavior is weird.
It switches spaces and also tabs in the IDE, so it makes two actions.

**Comment by lstkz** [comment]
Another use case:

a) I have two monitors
b) Monitor 1 has two spaces with two IDEs (the same situation from 1st post)
b) press `ctrl+~` in the Monitor 1 (switch between spaces)
c) focus Monitor 2 and go back to Monitor 1 (click with the mouse)
d) press G9 macro (ctrl+tab)
It works correctly.
If I skip the c) point, there will be a weird bug.
Is it possible that there is something wrong with tilde character?
Why does it work correctly without a macro?

**Comment by tatokis** [comment]
Do you have the right keyboard layout set in ckb? Settings tab -> keyboard layout

**Comment by lstkz** [comment]
Polish layout

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/15
