### ISSUE TITLE
Support pt-BR layout

### ISSUE THREAD

**Issue by rainerborene** [mattanger/ckb-next#165]
Continue https://github.com/ccMSC/ckb/issues/589

**Comment by rainerborene** [comment]
@tatokis why one are you referring?
![screen shot 2017-04-25 at 15 27 23](https://cloud.githubusercontent.com/assets/101501/25401288/bb913c2a-29cb-11e7-9b28-64c632621669.png)

**Comment by tatokis** [comment]
![22962c6f562c](https://cloud.githubusercontent.com/assets/6003656/25406704/551c23de-2a10-11e7-91a8-933771fef8fa.jpg)

**Comment by adrianosantanna** [comment]
Hi there, I'm arriving now and have one pt-BR K70 lux rgb keyboard.

Maybe I can help with some information about the keyboard, hoping someone can improve ckb-next to support pt-BR layout.

@tatokis, regarding your question (at https://github.com/ccMSC/ckb/issues/589) about the key next to the right shift, it appears that key is not mapped under ckb-next. Its light doesn't turn on and it doesn't work when ckb-next is installed and running.

I would be happy if I can provide additional information, just let me know.
