### ISSUE TITLE
CKB Uses ~30% of CPU

### ISSUE THREAD

**Issue by Maxattax97** [mattanger/ckb-next#166]
I tweaked around in the CKB configuration for awhile and determined that the largest factor by far was the hardware FPS.

I had a single pinwheel-searchlight animation with rainbow colors which is now disabled. While deleting the animation had no effect on CPU usage, reducing FPS definitely did. After decreasing my FPS from 30 to 5, my CPU usage now lingers around 2%. However, such high CPU usage does not seem normal to me for a mere LED animation...

I'm using a Scimitar RGB on Manjaro Linux with ckb beta-v0.2.7.

**Comment by tatokis** [comment]
Disable the animation preview

**Comment by frickler24** [comment]
Had you switched on the "Show animated" check on the lighting tab? I had additional load between 15% and 25%-points when checked.

**Comment by Maxattax97** [comment]
This helps when the configuration GUI is open, which disabling the animation preview _does_ help CPU usage. My issue was occurring when the GUI was closed. Today my mouse is running ~7% CPU with a pinwheel-searchlight animation at a reduced 15 FPS and GUI closed.

I'm not sure what to expect, but ~1% seems reasonable _to me_. I don't know if this is a bug, the result of unoptimized code, or what the most efficient solution can actually produce.

By the way, I don't mean to sound critical. This really is a phenomenal project and I'm very happy that the open source community has provided such a fine set of drivers for Corsair hardware. Thanks you guys.

**Comment by axettone** [comment]
I also have high CPU usage, even when GUI is closed. Reducing framerate from 30 to 10, CPU dropped from 20-22% to 7% (ckb process only), but I think it's still higher than what it should be.

**Comment by pjcv** [comment]
I did some experimenting and I found that getMuteState() is taking up quite a lot of time when running in linux. I see ckb taking about 3.5% CPU with it running, and 0.5% with it commented out. Can someone else try this out and confirm?
