### ISSUE TITLE
Music Visualization uses Audio IN insteal of Audio OUT when Audio IN is connected

### ISSUE THREAD

**Issue by Cyrus-Harding** [mattanger/ckb-next#172]

**Comment by tatokis** [comment]
Pulseaudio async API patches welcome or pavucontrol says it all.

**Comment by Cyrus-Harding** [comment]
Can you elaborate?

**Comment by Cyrus-Harding** [comment]
Never mind, installed pavucontrol and fixed it.

Thanks.

**Comment by Cyrus-Harding** [comment]
Wait, is there any way to lock the input source?

**Comment by fleischie** [comment]
Closing, because 1) this issue is not going anywhere and 2) I don't condone this way of communicating problems. :man_shrugging:
