### ISSUE TITLE
"Animation" script could not be loaded. Please check your animation directory

### ISSUE THREAD

**Issue by 15bitgames** [mattanger/ckb-next#178]
Hi I just updated ckb to the latest commit with the AUR package and now I seem to get

The "<name>" script could not be loaded. Please check your animation directory.

I've noticed that the AUR package installs it to /opt/ckb/ckb-animations.  Is this correct?

**Comment by ghost** [comment]
Thank you for reporting this.

Yesterday I merged the branches but definitely forgot to update the AUR package (some backwards-incompatible changes were introduced). I'll fix it ASAP.

**Comment by ghost** [comment]
Should be OK now.

**Comment by 15bitgames** [comment]
Thank you :)
