### ISSUE TITLE
Ship license with the product

### ISSUE THREAD

**Issue by ghost** [mattanger/ckb-next#185]
`LICENSE` must be shipped both on macOS and Linux with every `ckb-next` instance, including binary packages and pre-built packages.

- [ ] `quickinstall`
- [ ] `BUILD.md`
- [ ] AUR
- [x] Fedora @hevanaa 
- [ ] macOS `pkg`

**Comment by hevanaa** [comment]
LICENSE is already included in the Fedora package.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/16
