### ISSUE TITLE
CAPS-LOCK key freeze system

### ISSUE THREAD

**Issue by insideouting2** [mattanger/ckb-next#186]
OSX SIERRA
STRAFE

Pressing the CAPS_LOCK key causes the system to freeze for a few seconds each time you press any action with the mouse or keyboard.
I have to uninstall the CKB application completely and restart the computer.
If the key is not pressed everything works normally.
Already happened in the old version 2.0.6.
 
Thank you very much for your work.

**Comment by tatokis** [comment]
https://github.com/mattanger/ckb-next/issues/23#issuecomment-275820468
