### ISSUE TITLE
"No devices connected" (v0.2.8)

### ISSUE THREAD

**Issue by brendn** [mattanger/ckb-next#189]
Having trouble getting this to work with my K70 RGB and M65.  

I have tried both ckb-next-git and ckb-next-latest-git from the AUR and still encounter this problem.

The keyboard and mouse both work fine on my system, the main reason I am using this is to change the RGB colors.  I'm not sure why they aren't being detected.

**Comment by ghost** [comment]
Did you start/enable the daemon as the post-install note says?

**Comment by brendn** [comment]
My apologies, I did not! That fixed it, thanks.
