### ISSUE TITLE
Back and Forward buttons on mice not working

### ISSUE THREAD

**Issue by paraschadha** [mattanger/ckb-next#192]
Back and forward buttons are not working (special buttons 4 and 5) in Mac OS. 

If it isn't possible to get this running on mac (at least right now), does anyone have any workaround suggestions? Thus far the only functional solution I have is running is via an apple script in the program tab on keypress: 

Back:
```
osascript -e 'tell application "System Events" to keystroke "[" using command down'
```

Forward:
```
osascript -e 'tell application "System Events" to keystroke "]" using command down'
```

**OS**: macOS Sierra
**Device used**: M65 Pro

**Comment by ghost** [comment]
M65 RGB Pro here as well. macOS 10.12.5

This is a pretty brilliant solution. Thanks!

I also used this method for using the sniper button to open mission control, I hope there may be a better solutions but for now this works.

Mission Control
> osascript -e 'do shell script "/Applications/Mission\\ Control.app/Contents/MacOS/Mission\\ Control"'

**Comment by paraschadha** [comment]
@kchen13 Using the sniper button for mission control is brilliant! I'm going to throw that on mine as well!

**Comment by nyaray** [comment]
Clever hacks, but wouldn't a keyboard macro be simpler than doing stuff through osascript?

**Comment by ghost** [comment]
I tried macros before they didn't work. Oddly enough they don't work on Corsairs' official CUE software (beta) in macOS either.

**Comment by fleischie** [comment]
Is it possible, that Mac OS just doesn't interpret the appropriate signal/key events?
Does somebody have a non-corsair mice with back/forward buttons, that can check, whether it is specifically a Corsair Mice issue?

P.S.: I will ask a colleague, if I find one with a non-corsair mouse (or any mouse at all). :smile:

**Comment by ghost** [comment]
@fleischie 
I have Steelseries Rival 100, and yes, without Steelseries' software for macOS such buttons do not work. I didn't check it with this software though, however, I believe it is very similar to what they offer on Windows. I will check it during this day on Hackintosh so this is as close to real Mac as possible.

**Comment by ghost** [comment]
@fleischie 
@light2yellow is correct. I used a Logitech Performance MX mouse before and the back/forward buttons do not work without Logitech's software. As far as I know it looks like software regardless of vendor invokes the cmd+[ or cmd+] keyboard shortcuts.

**Comment by fleischie** [comment]
Standard USB mouse with side-buttons doesn't work either. So "normal" Mac behavior is not to map back/forward button -> back/forward OS event.

So what's the plan? Roll with Mac-like or coerce Windows/Linux-like behavior?

**Comment by mhennessie** [comment]
@paraschadha Thank you for the AppleScripts, they work perfectly and bring a much desired function back.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/19
