### ISSUE TITLE
Can't use a keyboard button and mouse scroll wheel simultaneously

### ISSUE THREAD

**Issue by paraschadha** [mattanger/ckb-next#193]
On macOS, in accessibility settings, I have zoom enabled (you use control and the scroll wheel at the same time to zoom into the screen). This, however, doesn't work when ckb is running!

When I quit ckb, it works just fine.

**OS**: macOS Sierra
**Keyboard**: K65 LUX
**Mouse**: M65 Pro (this bug has been recreated with other non-corsair mice as well)

**Comment by danybmx** [comment]
I think that this is related to #106 and #190.
Compile using the testing branch and check if it works after the quickinstall.

Regards!

**Comment by paraschadha** [comment]
@danybmx Compiled using the testing branch, unfortunately, this issue is not resolved.

Control + scroll wheel works perfectly without ckb (and ckb daemon) running. When ckb (and/or ckb launchdaemon) is running this no longer works.

**Comment by auibrian** [comment]
Karabiner also have this problem. I have been investigating but have no solution currently.

**Comment by TrolldadSATX** [comment]
I have found the same problem for zooming in and out in Adobe Illustrator.

**Comment by hoeegh** [comment]
Me too. But the issue only appears after a reboot. Everything works fine after installation, and after sleep/wake, but after a reboot this unintended behaviour appears. Uninstalling, rebooting and then reinstalling fixes the issue until next reboot.
