### ISSUE TITLE
Won't detect my k95

### ISSUE THREAD

**Issue by alejoacostaa** [mattanger/ckb-next#194]
Just grabbed a new k95 rgb platinum and for some reason it won't detect it, I already tried to restar the machine. any tips?

The keyboard works fine and RGB lights get turned on and all, but it simply won't get detected by ckb.

PD: I'm on a Hackintosh (running macOS on not native hardware), so that could be the issue. I also don't know if 3.0 ports work yet, so let me know how and ill check. Also, I'm running Sierra. 10.12.4

PD2: This is my USB window thingy:
https://content.screencast.com/media/4ca1a4fe-340f-4e77-9b9b-1a35572a631f_f1775fbc-3092-4e71-98fe-4ad297086ef9_static_0_0_2017-05-15_01-55-58.png

**Comment by tatokis** [comment]
The Platinum is partially supported on Linux #156 
and reported not working on macOS #180
