### ISSUE TITLE
K70 LUX RGB

### ISSUE THREAD

**Issue by siojima** [mattanger/ckb-next#198]
ckb.app crashes 2 seconds are opening, and just opens and closes on the tabs above. I am running OS X Yosemite Vers. 10.10.5. Not really sure as to why the app constantly crashes, but is there a solution? P.s The keyboard works fine on my PC but due to school reasons I can't always use my PC so I kinda need for this to work

**Comment by SethBarberee** [comment]
Can you give us more info please? What version of CKB are you running? The testing branch had a commit concerning the K70 LUX RGB 2 days ago. If you haven't done it yet, try the testing branch

**Comment by siojima** [comment]
I've been trying use the v0.2.8 and also this https://github.com/mattanger/ckb-next/tree/testing.

**Comment by SethBarberee** [comment]
Could you attach the output of ckb when you run it with this command?
`sudo launchctl unload /Library/LaunchDaemons/com.ckb.daemon.plist && sudo /Applications/ckb.app/Contents/Resources/ckb-daemon`

With the output, we might be able to see how and why it's crashing.

**Comment by siojima** [comment]
Sorry, not too sure what you're talking about. I'm not too good with that kind of stuff.

**Comment by ghost** [comment]
@siojima 
Open a new Terminal instance and paste the command:
```
sudo launchctl unload /Library/LaunchDaemons/com.ckb.daemon.plist && sudo /Applications/ckb.app/Contents/Resources/ckb-daemon
```
 After that, press Enter to execute.

Then open a second Terminal instance and execute:
```
/Applications/ckb.app/Contents/MacOS/ckb --close && /Applications/ckb.app/Contents/MacOS/ckb
```
Paste outputs from both terminals here.
