### ISSUE TITLE
CKB Next App with VoiceOver Accessibilities on MacOS 

### ISSUE THREAD

**Issue by BambooSnPandA** [mattanger/ckb-next#199]
Hi, 

I have been using CKB for a while now, but just recently went through the ckb app, and found out that it isn't fully accessible  with VoiceOver. 
The  VoiceOver cursor doesn't move everywhere where it needs to, and the radio buttons can't  be heard by VoiceOver.

If anyone could possibly help out with this, would be greatly appreciated.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/20
