### ISSUE TITLE
CKB Next desktop app closes seconds after it is opened OSX

### ISSUE THREAD

**Issue by willnuckles** [mattanger/ckb-next#201]
Installed v0.2.8 from Releases, and the desktop GUI closes about 3 seconds after it's opened. I've tried building from source with Qt only to be met with the same results.

Running OSX 10.11.6.

**Comment by willnuckles** [comment]
After manually running the `ckb` script located in the MacOS folder, this is the result. Looks like the culprit is a segmentation fault. 
![screen shot 2017-05-23 at 9 40 08 am](https://cloud.githubusercontent.com/assets/6243367/26359735/dc82a2da-3f9b-11e7-9e02-ee1305a46605.png)

**Comment by tatokis** [comment]
I have no idea how one goes about debugging MacOS programs, so I can't help.
Any chance of compiling from source to test? There is info on README on how to do it.

Also, that Apu reference is great.
CC @fleischie @light2yellow.

**Comment by ghost** [comment]
Going through a list of bugs, this seems to be a known one - https://bugreports.qt.io/browse/QTBUG-55005?jql=text%20~%20%22error%20receiving%20trust%20for%20a%20CA%20certificate%22

@willnuckles do you have admin privileges on that account?

Also, I hope that the segfault is not for some other reason. `.pkg` was built with Qt 5.8.x on macOS 10.12.4 in a VM, the only thing that was possible to test was that the app just launches.

Please try `gdb ckb`, even though most probably you have no Qt debug symbols, it might reveal something.

**Comment by willnuckles** [comment]
@tatokis, I did compile from source only to be met with the same results. 

@light2yellow, I do have admin privileges. I also installed Qt, and ran in debug mode to try to see where it was actually happening. I did get it to error out, but it seemed to break on a binary file, and I'm not Neo quite yet. I only got to look at it for 20 minutes before having to get back to work. 

Since I'm not a MacOS developer (just a web guy), can you recommend a good file/method to place a few breakpoints? Is not getting those certificates the biggest problem? 

I appreciate the help!

**Comment by tatokis** [comment]
@willnuckles you do not need to place any breakpoints.
Compile ckb-next with debug symbols (./qmake-auto && make debug), install gdb and then run it like this.
`gdb path/to/ckb/binary`
on the gdb prompt enter run like so
`(gdb) run`
and then it will start.

When it receives a SIGSEGV, it will return back to the gdb prompt, you should then enter 'bt full' and send us the output.

**Comment by willnuckles** [comment]
Will do! Give me a few days, and I'll send it over.

**Comment by ghost** [comment]
@willnuckles any updates on this?

**Comment by willnuckles** [comment]
No update. Got incredibly busy at work. Chalking this up to some restrictions placed on my work machine since a workmate receives the same issue on his work machine, but not his personal Mac.
