### ISSUE TITLE
No Device Detected on Arch

### ISSUE THREAD

**Issue by ghost** [mattanger/ckb-next#209]
I have put in the quirks into my GRUB under Arch Linux, but it shows both my K70R and Corsair Scimitar don't work.

This has worked fine under Ubuntu, but I compiled from source and it didn't work under Manjaro Arch.

**Comment by tatokis** [comment]
The AUR package specifically states you need to manually enable the systemd service

**Comment by ghost** [comment]
@tatokis I didn't see anything about the service in the AUR. But I got it.

Here's the steps I did for anyone else that is looking for this.
`sudo systemctl enable ckb-daemon`
`sudo systemctl start ckb-daemon`

**Comment by ghost** [comment]
Not sure how it is possible to miss it...
It is even painted with `makepkg` colours and emboldened :)

[![asciicast](https://asciinema.org/a/4wv61rdbq77seojgm6wsb7x6z.png)](https://asciinema.org/a/4wv61rdbq77seojgm6wsb7x6z)

**Comment by ghost** [comment]
I didn't realize Arch did that. I have only used Arch once in my life, give me a break. :(
