### ISSUE TITLE
"cmd" and "option" key not work in safari(10.12.5 (16F73)) with K65 RGB

### ISSUE THREAD

**Issue by Vxider** [mattanger/ckb-next#212]
"cmd" and "option" key not work in safari(10.12.5 (16F73)) with K65 RGB, I cannot open a new link in background using command + mouse click and close other link using option.
And when I using "CAPS LOCK" button, my computer(mac pro late 3013) will suspend for about 5 seconds.

----
I found a solution in #188
type "sudo killall ckb-daemon" in terminal can solve this problem

**Comment by tatokis** [comment]
#190 has a WIP fix.
