### ISSUE TITLE
OSX USB passthrough support

### ISSUE THREAD

**Issue by stevecookform3** [mattanger/ckb-next#215]
Would be great to enable use of the passthrough USB port on relevant models (e.g. the K65 LUX RGB). Currently while the keyboard is attached to OSX and ckb is working fine, the USB port is not detected (or even powered).

**Comment by tatokis** [comment]
Have you plugged in the second USB cable to your computer?
It's passthrough, not a hub.

**Comment by stevecookform3** [comment]
@tatokis clearly I'm having a senior moment.. it does indeed work if both keyboard USB connections are plugged in.
