### ISSUE TITLE
Gigabyte Aero 15W Support

### ISSUE THREAD

**Issue by Queatz** [mattanger/ckb-next#216]
Just got one of these and loving it.

What's the LOE for adding a new keyboard to this project?

Would love to be able to help.

**Comment by tatokis** [comment]
I'd say it's not easy trying to implement non-Corsair devices, as the protocol is most likely quite different.
You are free to fork the project and try changing to the protocol used by your device, however we can't really help.

If you do figure out the protocol for your device, you could create a daemon with the same interface as ours and then use the ckb GUI with it, but that's about it.

Some possibly helpful documentation:
https://doxygen.frickler24.de/ckb-daemon-full/
https://github.com/mattanger/ckb-next/blob/master/DAEMON.md
