### ISSUE TITLE
Key binding with Fn support.

### ISSUE THREAD

**Issue by Vxider** [mattanger/ckb-next#218]
Hope to support key binding with key combination.
Like Fn + F1 ...

**Comment by frickler24** [comment]
@Vxider it is on my to-do-list and I started a GUI implementation for it some months ago,
but it is at priority somewhere between x and z :-(

Do you have experience in designing GUIs with qt or implementing in c?

**Comment by Vxider** [comment]
Sorry, I am not good at GUI implementation.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/24
