### ISSUE TITLE
Have to "save to hardware" on every reboot to turn off side-lights

### ISSUE THREAD

**Issue by andrej-mitrovic-sociomantic** [mattanger/ckb-next#222]
I'm running Ubunty Xenial, and using a Corsair Strafe RGB. The ckb app starts on system start, and it turns off the backlights for the keys, as configured. However, there are also side-lights on this keyboard, and they're turned on until I open the ckb GUI and select "save to hardware".

Is there any way to fix this?

**Comment by frickler24** [comment]
@andrej-mitrovic-sociomantic What do you mean with side-lights? ![grafik](https://user-images.githubusercontent.com/6292952/26844757-cb6a22d4-4af4-11e7-94b1-e39d78973978.png)
And could you pls send me a screen shot where you configure it in the GUI?

**Comment by andrej-mitrovic-sociomantic** [comment]
![20170606_201803](https://user-images.githubusercontent.com/7713325/26844964-6bbb191e-4af5-11e7-97a1-ebe15aba216d.jpg)

![screenshot from 2017-06-06 20-18-46](https://user-images.githubusercontent.com/7713325/26844974-744fbabc-4af5-11e7-9e61-1382e35b181f.png)

I just have to open the GUI and click "Save to hardware" in order for those lights to turn off.

**Comment by ghost** [comment]
I guess it's a duplicate of #107.

**Comment by andrej-mitrovic-sociomantic** [comment]
Looks like it, thanks for the find!
