### ISSUE TITLE
Keyboard layout is not correct(K65 RGB Lux)

### ISSUE THREAD

**Issue by Vxider** [mattanger/ckb-next#223]
In key binding interface, "right window" key should be "Fn" key.

**Comment by LoganCalloway** [comment]
hey my k65 lux RGB want even pop up it says no device connected in ckb could you plz tell me how you got yours to show up.

**Comment by SethBarberee** [comment]
@LoganCalloway, this thread is not a support thread. Please open a issue for that.

@Vxider, could you provide us with more info about your system and possibly a screenshot of the GUI?

**Comment by Vxider** [comment]
My system version is macos  10.12.5 (Mac Pro Late 2013), here is my screenshot.

<img width="518" alt="screenshot" src="https://user-images.githubusercontent.com/6134315/27016037-6b0eb0a0-4f4d-11e7-89c3-34ed9f0a299b.png">

And here is my keyboard



![img_5322](https://user-images.githubusercontent.com/6134315/27016062-ee4775a6-4f4d-11e7-8e00-4274bcc674a9.jpg)

**Comment by ghost** [comment]
Please, try `newdev` branch. The commit that is supposed to fix this is https://github.com/mattanger/ckb-next/commit/cfc175070f26f47b100e7e8cb8f273b4377c2849.

**Comment by ghost** [comment]
@Vxider Any success?

**Comment by Vxider** [comment]
Sorry, my keyboard can not be tested due to water damage. Hope others can help to test.

**Comment by tatokis** [comment]
Should be fixed
