### ISSUE TITLE
Corsair Glaive

### ISSUE THREAD

**Issue by white82934** [mattanger/ckb-next#225]
Mouse doesn't work on latest build of Ubuntu Gnome 
[ckb-dev-detect-report.gz](https://github.com/mattanger/ckb-next/files/1063373/ckb-dev-detect-report.gz)

**Comment by ryanadean** [comment]
Same for me, I posted in the Unsupported Devices thread as well, as a heads up =)

**Comment by tatokis** [comment]
I am giving this a higher priority, as judging by the error in dmesg, I assume the mouse doesn't work on Linux at all without the driver.
The dev detect script reported firmware version 1.03, which requires a work around.

I have added the mouse as an M65 in the glaive branch.
Until further work can be done on it, that should be enough to get it up and running on Linux, even though one RGB zone will not function.

https://github.com/mattanger/ckb-next/tree/glaive

**Comment by Gnork** [comment]
I installed the ckb-next from the glaive branch, but the mouse still does not function at all for me on Fedora 25 (kernel 4.11).

* ckb-next GUI not showing it.
* mouse does not react at all (no clicking/moving)
* rgb not lighting (except for the small blue DPI indicators)

Output from `journalctl  -u ckb-daemon`.  It does detect my keyboard, but not the mouse:

```
Jun 12 10:59:39 localhost.localdomain ckb-daemon[1273]: [I] Connecting Corsair STRAFE RGB Gaming Keyboard at /dev/input/ckb1
Jun 12 10:59:39 localhost.localdomain ckb-daemon[1273]: [I] Connecting Corsair STRAFE RGB Gaming Keyboard at /dev/input/ckb1
Jun 12 10:59:39 localhost.localdomain ckb-daemon[1273]: [I] claiming interfaces. name=Corsair STRAFE RGB Gaming Keyboard, serial=0602500EAEBD18415619390EF5001943, firmware=0205; Got >> 3<< as ep_str
Jun 12 10:59:39 localhost.localdomain ckb-daemon[1273]: [I] claiming 3 endpoints
Jun 12 10:59:39 localhost.localdomain ckb-daemon[1273]: [I] Starting input thread for /dev/input/ckb1
Jun 12 10:59:44 localhost.localdomain ckb-daemon[1273]: [E] os_usbrecv (via firmware.c:15): Connection timed out
Jun 12 10:59:44 localhost.localdomain ckb-daemon[1273]: [W] _start_dev (device.c:38): Unable to load firmware version/poll rate
Jun 12 10:59:44 localhost.localdomain ckb-daemon[1273]: [I] Setup finished for /dev/input/ckb1
```

lsusb (Bus 001 Device 006 is the mouse):

```
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 0451:8140 Texas Instruments, Inc. TUSB8041 4-Port Hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 0451:8142 Texas Instruments, Inc. TUSB8041 4-Port Hub
Bus 001 Device 006: ID 1b1c:1b34 Corsair 
Bus 001 Device 003: ID 145f:01d9 Trust 
Bus 001 Device 007: ID 1b1c:1b20 Corsair 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Please let me know, how I can contribute useful information about this.

**Comment by tatokis** [comment]
@Gnork Apologies, it appears I forgot to add it as a mouse.
Do a git pull and try again.

**Comment by Gnork** [comment]
I tried it, but nothing changed.

**Comment by tatokis** [comment]
@Gnork Apologies again, I really dropped the ball on this one.
Try again please.

**Comment by Gnork** [comment]
@tatokis Still no change. Even the journalctl output does not show something new.

By the way, you don't need to apologize. I think it's amazing that you work on this and I'm glad to help you sort this out.

**Comment by tatokis** [comment]
@Gnork any chance you're not running the right binary, or maybe not the right code?
The daemon should have at least tried to claim the new device.

Perhaps you can try manually running it from the tree? `sudo ./bin/ckb-daemon`

**Comment by Gnork** [comment]
1. I confirmed that I'm on the correct branch, by taking a look at the source code and saw your changes there.
2. I run ./quickinstall and the binary ./bin/ckb-daemon is updated (confirmed by the timestamp)
3. I stop the running instance with `systemctl stop ckb-daemon`
4. I run the binary manually with `sudo ./bin/ckb-daemon` from the git directory.

This is the output from the manual run:

```
    ckb: Corsair RGB driver beta-v0.2.8+testig
[I] Root controller ready at /dev/input/ckb0
[I] >>>vendor = 0x1b1c, product = 0x1b20, path = /dev/bus/usb/001/002, syspath = /sys/devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-2
[I] Connecting Corsair STRAFE RGB Gaming Keyboard at /dev/input/ckb1
[I] Connecting Corsair STRAFE RGB Gaming Keyboard at /dev/input/ckb1
[I] claiming interfaces. name=Corsair STRAFE RGB Gaming Keyboard, serial=0602500EAEBD18415619390EF5001943, firmware=0205; Got >> 3<< as ep_str
[I] claiming 3 endpoints
[I] Starting input thread for /dev/input/ckb1
[E] os_usbrecv (via firmware.c:15): Connection timed out
[W] _start_dev (device.c:38): Unable to load firmware version/poll rate
[I] Setup finished for /dev/input/ckb1
```

**Comment by tatokis** [comment]
I wonder if this has something to do with it, try unplugging your strafe and your glaive, start the daemon and plug the glaive in only.

Either that, or I am completely missing something.

**Comment by Gnork** [comment]
I tried it by only using my old logitech keyboard now.
ckb-daemon does not show any reaction when plugging in the mouse after starting it.

[ckb-dev-detect-report.gz](https://github.com/mattanger/ckb-next/files/1068097/ckb-dev-detect-report.gz)

The mouse shows up in the ckb-dev-detect-report.

**Comment by Gnork** [comment]
With my pull request above, the mouse is functional now. All buttons and mouse movement are working.
@tatokis Thanks a lot for your help :)

Now that the mouse is being detected, the ckb-next GUI software suggests a firmware update. I guess this firmware update is only for the M65 and installing might brick the GLAIVE. This should be disabled somehow, until the GLAIVE is added properly as a separate device, to avoid serious issues.

**Comment by tatokis** [comment]
@Gnork Don't worry, the daemon refuses to install firmware updates for the wrong devices.
In the future I will add the glaive as its own device with the right GUI image, but until I can get to that, this should be sufficient.

**Comment by edflores28** [comment]
@tatokis i have a glaive mouse and I am interested in contributing. Based on your previous comments it looks like there is more work to be done. Is there any direction you can give on where to start?
Thanks

**Comment by ghost** [comment]
Is there any support for the Corsair glaive on macOS? The fix above seems to only be for Linux unless I am mistaken. I don't have any coding experience, so following this thread was very confusing...

**Comment by tatokis** [comment]
@BIRDMOMSENPAI Try the newdev branch and tell us what works and what doesn't.

**Comment by tatokis** [comment]
@edflores28 Apologies for being late, did not see your message.
You could try adding it as its own category in the daemon and then modify the GUI accordingly.
There's a recent-ish commit in the newdev branch that does exactly that with the k63 so you could use that as a guide.

**Comment by ghost** [comment]
@tatokis I'm really sorry, but I'm not sure what I should be doing lol. I downloaded the newdev branch, but what should I do from here?

**Comment by mikevelez** [comment]
My glaive doesn't work, can anyone tell me why?:

```
ckb-dev-detect - Mon Jul 17 09:52:26 CDT 2017

Kernel: Linux MeMReS-PC 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

OS Version:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

USB Devices:
Couldn't open device, some information will be missing

Bus 005 Device 009: ID 1b1c:1b34 Corsair 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1b1c Corsair
  idProduct          0x1b34 
  bcdDevice            1.03
  iManufacturer           1 
  iProduct                2 
  iSerial                 3 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           84
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              300mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      58
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               8
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     172
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      25
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1

Dmesg on current boot:
Jul 17 09:29:38.744050 MeMReS-PC kernel: usb 3-1: New USB device found, idVendor=1b1c, idProduct=1b34
Jul 17 09:29:38.744163 MeMReS-PC kernel: usb 3-1: Product: Corsair Gaming GLAIVE RGB Mouse
Jul 17 09:29:38.744209 MeMReS-PC kernel: usb 3-1: Manufacturer: Corsair
Jul 17 09:29:38.744264 MeMReS-PC kernel: input: Corsair Corsair Gaming GLAIVE RGB Mouse as /devices/pci0000:00/0000:00:1c.2/0000:06:00.0/usb3/3-1/3-1:1.0/0003:1B1C:1B34.0006/input/input24
Jul 17 09:29:38.744349 MeMReS-PC kernel: hid-generic 0003:1B1C:1B34.0006: input,hidraw5: USB HID v1.11 Mouse [Corsair Corsair Gaming GLAIVE RGB Mouse] on usb-0000:06:00.0-1/input0
Jul 17 09:29:38.744438 MeMReS-PC kernel: hid-generic 0003:1B1C:1B34.0007: item 0 1 0 8 parsing failed
Jul 17 09:29:38.744450 MeMReS-PC kernel: hid-generic: probe of 0003:1B1C:1B34.0007 failed with error -22
Jul 17 09:37:12.940282 MeMReS-PC kernel: usb 5-1.4: New USB device found, idVendor=1b1c, idProduct=1b34
Jul 17 09:37:12.940616 MeMReS-PC kernel: usb 5-1.4: Product: Corsair Gaming GLAIVE RGB Mouse
Jul 17 09:37:12.940760 MeMReS-PC kernel: usb 5-1.4: Manufacturer: Corsair
Jul 17 09:37:12.944046 MeMReS-PC kernel: input: Corsair Corsair Gaming GLAIVE RGB Mouse as /devices/pci0000:00/0000:00:1c.3/0000:07:00.0/usb5/5-1/5-1.4/5-1.4:1.0/0003:1B1C:1B34.0008/input/input25
Jul 17 09:37:12.944372 MeMReS-PC kernel: hid-generic 0003:1B1C:1B34.0008: input,hidraw0: USB HID v1.11 Mouse [Corsair Corsair Gaming GLAIVE RGB Mouse] on usb-0000:07:00.0-1.4/input0
Jul 17 09:37:12.948206 MeMReS-PC kernel: hid-generic 0003:1B1C:1B34.0009: item 0 1 0 8 parsing failed
Jul 17 09:37:12.948256 MeMReS-PC kernel: hid-generic: probe of 0003:1B1C:1B34.0009 failed with error -22
Jul 17 09:48:10.396220 MeMReS-PC kernel: usb 5-1.4: New USB device found, idVendor=1b1c, idProduct=1b34
Jul 17 09:48:10.396577 MeMReS-PC kernel: usb 5-1.4: Product: Corsair Gaming GLAIVE RGB Mouse
Jul 17 09:48:10.396809 MeMReS-PC kernel: usb 5-1.4: Manufacturer: Corsair
Jul 17 09:48:10.400024 MeMReS-PC kernel: input: Corsair Corsair Gaming GLAIVE RGB Mouse as /devices/pci0000:00/0000:00:1c.3/0000:07:00.0/usb5/5-1/5-1.4/5-1.4:1.0/0003:1B1C:1B34.000B/input/input27
Jul 17 09:48:10.400331 MeMReS-PC kernel: hid-generic 0003:1B1C:1B34.000B: input,hidraw0: USB HID v1.11 Mouse [Corsair Corsair Gaming GLAIVE RGB Mouse] on usb-0000:07:00.0-1.4/input0
Jul 17 09:48:10.400541 MeMReS-PC kernel: hid-generic 0003:1B1C:1B34.000C: item 0 1 0 8 parsing failed
Jul 17 09:48:10.400571 MeMReS-PC kernel: hid-generic: probe of 0003:1B1C:1B34.000C failed with error -22

Dmesg on last boot:


Daemon on current boot:
-- Logs begin at Mon 2017-07-17 09:28:48 CDT, end at Mon 2017-07-17 09:51:02 CDT. --
Jul 17 09:47:44.876063 MeMReS-PC systemd[1]: Started Corsair Keyboard Daemon.
Jul 17 09:47:44.876688 MeMReS-PC ckb-daemon[30910]:     ckb: Corsair RGB driver v0.2.8
Jul 17 09:47:44.876821 MeMReS-PC ckb-daemon[30910]: [I] Root controller ready at /dev/input/ckb0

Daemon on last boot:
Specifying boot ID has no effect, no persistent journal was found
```

**Comment by SethBarberee** [comment]
@mikevelez 
Which branch did you download from? 
`master` doesn't have Glaive support however `newdev` has **experimental** support
Try downloading the `newdev` branch and see if that works.

**Comment by mikevelez** [comment]
That did work perfectly, I am now able to use my Glaive in Ubuntu now, thanks!

**Comment by tatokis** [comment]
I have added proper support for the Glaive in the newdev branch.
It would be appreciated if someone could test it and report back with what works and what doesn't.

All three RGB zones should now function.

**Comment by Gnork** [comment]
Hey,

I pulled the new code, but the third RGB zone is still not working. I can select a color with the color-picker, but neither the small dot in the GUI, nor the actual LED are working.

Below is the output of `journalctl -u ckb-daemon`, maybe you see something that's helping. I also started the ckb GUI tool from the commandline, but it doesn't show any errors.

```
Aug 07 18:53:43 localhost.localdomain systemd[1]: Started Corsair Keyboard Daemon.
Aug 07 18:53:43 localhost.localdomain ckb-daemon[1442]:     ckb: Corsair RGB driver beta-v0.2.8
Aug 07 18:53:43 localhost.localdomain ckb-daemon[1442]: [I] Root controller ready at /dev/input/ckb0
Aug 07 18:53:43 localhost.localdomain ckb-daemon[1442]: [I] >>>vendor = 0x1b1c, product = 0x1b20, path = /dev/bus/usb/001/002, syspath = /sys/devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-1
Aug 07 18:53:43 localhost.localdomain ckb-daemon[1442]: [I] >>>vendor = 0x1b1c, product = 0x1b34, path = /dev/bus/usb/001/003, syspath = /sys/devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-7
Aug 07 18:53:43 localhost.localdomain ckb-daemon[1442]: [I] Connecting Corsair STRAFE RGB Gaming Keyboard at /dev/input/ckb1
Aug 07 18:53:43 localhost.localdomain ckb-daemon[1442]: [I] claiming interfaces. name=Corsair STRAFE RGB Gaming Keyboard, firmware=0205; Got >> 3<< as ep_str
Aug 07 18:53:43 localhost.localdomain ckb-daemon[1442]: [I] claiming 3 endpoints
Aug 07 18:53:43 localhost.localdomain ckb-daemon[1442]: [I] Connecting Corsair Gaming GLAIVE RGB Mouse at /dev/input/ckb2
Aug 07 18:53:43 localhost.localdomain ckb-daemon[1442]: [I] claiming interfaces. name=Corsair Gaming GLAIVE RGB Mouse, firmware=0103; Got >> 3<< as ep_str
Aug 07 18:53:43 localhost.localdomain ckb-daemon[1442]: [I] claiming 3 endpoints
Aug 07 18:53:43 localhost.localdomain ckb-daemon[1442]: [I] Starting input thread for /dev/input/ckb2
Aug 07 18:53:43 localhost.localdomain ckb-daemon[1442]: [I] Starting input thread for /dev/input/ckb1
Aug 07 18:53:45 localhost.localdomain ckb-daemon[1442]: [I] Setup finished for /dev/input/ckb2
Aug 07 18:53:49 localhost.localdomain ckb-daemon[1442]: [E] os_usbrecv (via firmware.c:15): Connection timed out
Aug 07 18:53:49 localhost.localdomain ckb-daemon[1442]: [W] _start_dev (device.c:38): Unable to load firmware version/poll rate
Aug 07 18:53:49 localhost.localdomain ckb-daemon[1442]: [I] Setup finished for /dev/input/ckb1
```

Edit:

There are two other things, which are not working:
1. The small button under the mouse wheel controls the DPI setting of the mouse. If I press the button multiple times it goes from 3 to 4 to 5 and should then cycle to 1. This works if only the daemon is running but not if the ckb GUI is running as well.

2. I saw in the git log, that there should be a new GLAIVE artwork, but it has not changed in the GUI.

**Comment by tatokis** [comment]
Which zone is the third non-functioning one? (Logo, front or side?)

**Comment by tatokis** [comment]
Also, sorry, didn't see the edit in the email, what do you get if you do `cat /dev/input/ckb2/features`?

**Comment by Gnork** [comment]
$ cat /dev/input/ckb2/features
corsair m65 rgb pollrate adjrate bind notify fwversion fwupdate

The non-functional RGB zone is the stripes at the side.

**Comment by tatokis** [comment]
Apologies, made a correction in https://github.com/mattanger/ckb-next/commit/42f4f2da7fad0d47a8a44655b31a6ab3b3acb197
Please try again with the latest code.

**Comment by Gnork** [comment]
I tried the new code but nothing changed.

**Comment by tatokis** [comment]
One more time, please.
https://github.com/mattanger/ckb-next/commit/40b2c7998c7df2adc413644da73d837ba78f64c1

**Comment by Gnork** [comment]
Ok, now the new artwork is showing up. But the only RGB zone working is now the one at the front. The left side RGB is still standard Yellow and the Logo is completely off. DPI cycling still not working.

```bash
$ cat /dev/input/ckb2/features
corsair glaive rgb pollrate adjrate bind notify fwversion fwupdate
```

**Comment by tatokis** [comment]
I am aware of the DPI button not cycling, it is on the TODO list to be implemented before the next release.
This should hopefully correct the RGB Zones, https://github.com/mattanger/ckb-next/commit/cf382adc20fd02f422053355688e34aec3ccb1fe

**Comment by Gnork** [comment]
This fixed the logo but not the side.

**Comment by Gnork** [comment]
Also the DPI indicator will be turned off now, when starting the ckb GUI, which has not happended before. Maybe you mixed up the side with the DPI indicator.

**Comment by tatokis** [comment]
@Gnork would you mind dropping by our IRC room? It would be easier to investigate this further.
(#ckb-next/irc.freenode.net / http://webchat.freenode.net/?channels=%23ckb-next&uio=d4)

**Comment by Gnork** [comment]
Hey, I have lot of stuff todo today, but I could be in the IRC room at about 23:00 CET.

What do you think about creating a new branch to investigate this and put some printf statements into the code, to get more debugging information. Then I could run the code for you later tonight, when I'm at home.

**Comment by tatokis** [comment]
It's less debugging and more sending commands to the daemon to see which ones control the physical lights on the device, and then telling the GUI to use those instead.

I was also not aware the stripes on the left were DPI indicators, so there's that.

**Comment by Gnork** [comment]
I think you misunderstood me with the DPI indicator:

The DPI indicators are the five small rectangles in the middle area of the mouse. They should always light up blue and have for example 3 of 5 rectangles glowing and 2 of 5 being turned off to indicate the DPI setting (that's how it works on Windows). But with your latest changes all of the rectangles get turned off when starting the ckb GUI, that's why I thought that you mixed something up (but I could be completely wrong).

The long stripes at the side are no DPI indicators. They are still only yellow (standard color) and do not change at all.

**Comment by tatokis** [comment]
Yeah, I only realised that later on, but it still doesn't explain why the latest changes affected the DPI indicators. I've only been trying to get the side RGB zones to work.

**Comment by Gnork** [comment]
I'm in IRC now.

**Comment by tatokis** [comment]
@Gnork This will hopefully get it working https://github.com/mattanger/ckb-next/commit/c1d009cff4241dce71aa033fb0ff8a224d168d95

**Comment by Gnork** [comment]
@tatokis The side color is working now 👍 Awesome work.

**Comment by F1nny** [comment]
Working great in newdev! Though just to confirm you guys are aware of the 5 DPI step lights not functioning and the change DPI button options are only up OR down (so when the default up is pressed gets crazy high but won't loop back around haha), as that should loop back on itself after the 5th DPI step setting right? Just wanted to confirm you guys were aware of those two items as look to be final two things for 100% glaive support!:) The 5 DPI lights (none lit) and the DPI setting looping back -Thanks guys amazing work, thanks for carrying on CKB!!

Just noticed comments above RE the DPI lights not working, looks like you guys are aware on that one! Then that when set to the default "DPI Up" for the DPI selector button it just goes up and up but never back down! If I can assist in providing any information just let me know! @tatokis 
Note the side color is working and configurable, just the 5 step DPI lights still unlit!

**Comment by Gnork** [comment]
DPI settings looping is confirmed to not be working yet.

The thing about the DPI lighting is strange though. They have been working during the last week on my Glaive without any problems. On the other hand, I have seen them being turned off completely, while I was testing various ckb versions for @tatokis the week before. It just started working afterwards, so I thought this was some random glitch.

@F1nny Do the DPI lights work, if you quit the CKB GUI?

**Comment by SethBarberee** [comment]
@Gnork 
Could you try out PR #284 and see if that fixes your issue? Feedback in the PR would be appreciated!

**Comment by Gnork** [comment]
Hey, sorry for the late response @SethBarberee 
I tested your pull request for the newdev branch and it works perfectly. It cycles through the DPI settings as intended.
Thanks for fixing this :)

**Comment by SethBarberee** [comment]
I'm not gonna take credit for someone else's work. That PR was good work on @pjcv 's part.

**Comment by Uskdara** [comment]
I just switched to Ubuntu from Windows cause I'm not a big fan of Windows 10.  I have a Glaive and I installed the newdev branch but the glave connects and works for about 5 seconds, then disconnects from the device list in CKB GUI and quits working for 5 seconds, and rinse and repeat over and over.  Anyone else having this issue or have any idea what might be causing it.  I've tried different USB ports to no avail.

**Comment by jackynikola** [comment]
Hey, guys. I have a problem with Glaive.  In CKB it doesn't recognise mouse. It is disconnected. I am running OS Sierra and I installed from newdev. Any solution besides one explained in files?

**Comment by tatokis** [comment]
@jackynikola not sure, it should work https://github.com/mattanger/ckb-next/blob/newdev/src/ckb-daemon/usb_mac.c#L870

Can you perhaps get some logs from the daemon? (I don't remember how, on mac, maybe someone more familiar can chime in.)

@Uskdara also check logs. If not sure how, run ckb-dev-detect from the repository.

**Comment by jackynikola** [comment]
Thanx for help  Tatokis.  The mouse is working as well as led but since I cant adjust dpi and remove lights its useless to me. Maybe I did instal wrong.  SO I went to quick instal. Then I installed CKB_next. Is that correct?

**Comment by jackynikola** [comment]
Thanx for help Tatokis. The mouse is working as well as led but since I cant adjust dpi and remove lights its useless to me.
![screen shot 2017-09-22 at 12 20 34 pm](https://user-images.githubusercontent.com/32183176/30756462-76f655f6-9f90-11e7-8baa-48e3d4239874.png)

**Comment by superherointj** [comment]
Installed ckb-next newdev branch on Ubuntu 17.04 and confirmed support to Corsair Glaive mouse. But the strong lights/led is quite annoying. Is there a way to disable it? Can you suggest a path forward to have the strong lights fixed?
The GUI also crashed when I tried to click on something.

Update: By keeping CLK app closed the annoying LED lights are gone and I am happy. I am really happy this solved my problem! Thank you for sharing this driver. It works!

**Comment by Maw1395** [comment]
This is amazing. Thank you so much!

**Comment by markdrake** [comment]
Thank you so much, my new mouse didn't work and this was the solution, I owe you a beer :)

**Comment by tatokis** [comment]
Glaive is now supported in master.
