### ISSUE TITLE
Strafe Keyboard - USB Passthrough

### ISSUE THREAD

**Issue by gemantzu** [mattanger/ckb-next#227]
Is it supposed to work? 
OS: Solus

**Comment by tatokis** [comment]
If it is passthrough, plug the second cable in. The driver has nothing to do with passthrough.
If it is a hub, it's a whole other story

**Comment by gemantzu** [comment]
It is passthrough, the second cable is always connected to the usb 3.0 port as it was on windows. I also tried with a usb 2.0 port (as it is a usb 2.0 passthrough) but still not working.

PS. Ok, nevermind, I had to restart the keybord so it would work. As an info, it is not working on usb 3.0 on Linux. So you have to unplug all ports of the keyboard, and plug both cables in a usb 2.0 end.
