### ISSUE TITLE
Update problems

### ISSUE THREAD

**Issue by Kylesaki** [mattanger/ckb-next#241]
I just bought a K95 Platinum, and when I launch CKB it says that I have to update, but when I do, the progress bar stops at full and my keyboard completely stops working. However, when I close the program, it works just fine. I am on Mac OSX Sierra 10.12.3

**Comment by tatokis** [comment]
That's a known bug, as support for the K95 Platinum is experimental and only in the newdev branch (as I assume you compiled from source).
You can test out and subscribe to #220 for further updates.
