### ISSUE TITLE
Wrong profile without CKB open

### ISSUE THREAD

**Issue by M4R10zM0113R** [mattanger/ckb-next#242]
Saving to hardware and then quitting the software seems to make it change to a very low DPI setting with all colors set to clear teal/factory default, 2 mice with same behavior:
1. Sabre RGB
2. Scimitar RGB

Some background:
Changing from ckb (base project) to ckb-next (fork/community) didn't bring the issue up, since ckb used to not provoke the problem when the (Qt) program wasn't open.
Scimitar was configured purely on ckb-next
Sabre was used on both ckb (base project) and ckb-next (fork/community).

Steps:
1. Install ckb-next
2. Start the ckb-daemon
3. Start ckb (Qt app)
4. Plug a supported mouse
5. Configure a profile
6. Save to Hardware
7. Quit ckb (Qt app)

**Comment by ghost** [comment]
Could you explain the problem in more detail? There's a daemon, called `ckb-daemon` and a frontend for it, `ckb`. The binaries were not renamed so far to `ckb-next`. AFAIK you won't have animations on mouse unless you have `ckb` running. The daemon is used to control the device while GUI is used for different dynamic configurations.

Could you write steps to reproduce the issue? This will help a lot to answer the first question.

**Comment by ghost** [comment]
So, `Save to hardware` basically resets the device? And you cannot configure it in any way because every time you try to save the configuration it gets reset?

Can we also see the output of `ckb-dev-detect` from the root of the source code tree?

**Comment by ghost** [comment]
Does your problem look similar to the one on #208?

**Comment by M4R10zM0113R** [comment]
Let me explain:
The "Save to Hardware" feature in ckb-next doesn't stick to the mouse but instead sets it to the low-dpi profile mentioned earlier (it is the reset profile on lighting, but not on DPI), rather than to the profile I specified when saving. I tried saving multiple profiles, resetting profiles in ckb, reinstalling all together, to get the same relative results (both mice)

**Comment by M4R10zM0113R** [comment]
And to answer the #208 question: It's precisely that, but to the low-DPI spectrum. This however didn't happen with ccMSC's ckb. It saved to hardware, and the profile stuck to the mouse whenever I plugged it into any other 3rd party computer without CKB/Corsair CUE

**Comment by tatokis** [comment]
Can you please do a git bisect on this?
This should be a good start commit https://github.com/mattanger/ckb-next/commit/34cd4c8920fbd3dc5d8dc4148da24edd515864b1

**Comment by M4R10zM0113R** [comment]
is there any way to reflash to default on the mice? I wanna get rid to as many factors as possible on the bisection

**Comment by M4R10zM0113R** [comment]
Excuse my dirty work/lack of git knowledge beforehand.
I bisected the project from 34cd4c8 to the latest.
Attached files have a file I made and a zip containing ".git/refs/bisect" 's contents.
[bisect-refs.zip](https://github.com/mattanger/ckb-next/files/1113953/bisect-refs.zip)
[bisect.txt](https://github.com/mattanger/ckb-next/files/1113954/bisect.txt)
(PS: Forgot to mention that I reset the mice per bisection, and that latest won't let me set DPIs while Qt app is on... I believe I may have missed a few more.)

**Comment by M4R10zM0113R** [comment]
sorry @light2yellow , I oversaw the ckb-dev-detect part...
here it is:
[ckb-dev-detect-report.gz](https://github.com/mattanger/ckb-next/files/1114021/ckb-dev-detect-report.gz)

**Comment by tatokis** [comment]
Thank you for your time and the detailed bisect.
This is clearly a regression caused by one of the indicator bugfix commits.
CC @frickler24

**Comment by AaronBottegal** [comment]
I have a new scimitar RGB, if anyone has any patches to fix it, I'll test them. I see the same behavior, have to keep the daemon running or it goes low DPI with nothing happening color-wise. I'll test any patches you want to see if it fixes the issue.

**Comment by tatokis** [comment]
@AaronBottegal check out #308, see if it helps.
