### ISSUE TITLE
K95 Platinum Shift and Ctrl key bindings locked together

### ISSUE THREAD

**Issue by kac487** [mattanger/ckb-next#248]
I have been trying to use my K95P with CKB but was unable to get the keyboard to respond after starting the ckb-daemon on the master branch. After reading some of the other issues, i switched over to the newdev branch. This allows the keyboard to work with CKB running, but my "Shift" and "Ctrl" keys are bound together somehow. Even when I re-assign the "Shift" key, the "Ctrl" key gets re-assigned to the same assignment (and vice-versa). I am running on Ubuntu 16.04

Here's the dev report and an image of the problem.
[ckb-dev-detect-report.gz](https://github.com/mattanger/ckb-next/files/1122738/ckb-dev-detect-report.gz)

![image](https://user-images.githubusercontent.com/14209034/27838817-f0cce60c-60ba-11e7-9fa0-8386dc71233d.png)

Any help is greatly appreciated.

**Comment by tatokis** [comment]
Can you control the lighting on each key of the four "Ctrl" keys, or is lighting on those keys bound together too?

**Comment by coljac** [comment]
I'll put this here in case it's a duplicate. With a regular K95 on Mac OS, using v0.2.8, I can't bind either the left shift or caps lock key without binding the other. As soon as I select one, the other becomes also bound, and unassigning does the same.

**Comment by kac487** [comment]
I managed to resolve this issue by clearing the ckb.conf file under my home directory. I have been trying to reproduce the problem but haven't had any luck.

**Comment by tatokis** [comment]
Could you please upload the old ckb.conf?
Are you using a custom version of Qt?
