### ISSUE TITLE
CKB Not Detecting Scimitar Pro

### ISSUE THREAD

**Issue by mgw1214** [mattanger/ckb-next#257]
I'll start off by saying I'm not good with computers at all. That being said, I followed the instructions for installing CKB, but it doesn't seem to be detecting my Scimitar Pro. I'm not sure if that mouse isn't supported, or if it's similar enough to the original Scimitar where it should be working, but I did something wrong or am missing something.

Any help would be appreciated! Thanks!

**Comment by SethBarberee** [comment]
@mgw1214 
Can you give more info about your system? OS? Installation method? (There is an Issue Template for a reason ;)

When you installed CKB-next, there should be a script called `ckb-dev-detect`. Can you run that and post its output?

**Comment by mgw1214** [comment]
I apologize for not using the template.

I am running macOS Sierra. I installed CKB-next through the quickinstall script, which generated two warnings but no errors it seems. I've tried rebooting and uninstalling/reinstalling and nothing appears under CKB except for settings, which states no devices connected. Here's the output from the script:

OS Version:
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67

USB Devices:
        Corsair Gaming SCIMITAR PRO RGB Mouse:

          Product ID: 0x1b3e
          Vendor ID: 0x1b1c  (CORSAIR MEMORY INC.)
          Version: 1.09
          Serial Number:
          Speed: Up to 12 Mb/sec
          Manufacturer: Corsair
          Location ID: 0x14200000 / 8
          Current Available (mA): 500
          Current Required (mA): 300
          Extra Operating Current (mA): 0

**Comment by SethBarberee** [comment]
> two warnings

What warnings? They might be important

**Comment by mgw1214** [comment]
2 warnings generated.
In file included from settingswidget.cpp:5:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
settingswidget.cpp:143:47: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_capsBox_activated(int index){
                                              ^
settingswidget.cpp:147:48: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_shiftBox_activated(int index){
                                               ^
settingswidget.cpp:151:47: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_ctrlBox_activated(int index){
                                              ^
settingswidget.cpp:155:46: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_altBox_activated(int index){
                                             ^
settingswidget.cpp:159:46: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_winBox_activated(int index){
                                             ^
3 warnings generated.
3 warnings generated.
7 warnings generated.
In file included from kblight.cpp:5:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from kbprofile.cpp:1:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
kbanimwidget.cpp:151:94: warning: unused parameter 'previous' [-Wunused-parameter]
void KbAnimWidget::on_animList_currentItemChanged(QListWidgetItem *current, QListWidgetItem *previous){
                                                                                             ^
2 warnings generated.
kbanim.cpp:333:32: warning: unused parameter 'bg' [-Wunused-parameter]
static float blendNormal(float bg, float fg){
                               ^
1 warning generated.
animadddialog.cpp:28:46: warning: unused parameter 'index' [-Wunused-parameter]
void AnimAddDialog::on_animBox_activated(int index){
                                             ^
1 warning generated.
1 warning generated.
animsettingdialog.cpp:487:57: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_delayBox_valueChanged(double arg1){
                                                        ^
animsettingdialog.cpp:491:58: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_repeatBox_valueChanged(double arg1){
                                                         ^
animsettingdialog.cpp:495:59: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_kpDelayBox_valueChanged(double arg1){
                                                          ^
animsettingdialog.cpp:499:60: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_kpRepeatBox_valueChanged(double arg1){
                                                           ^
animsettingdialog.cpp:503:58: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_kpReleaseBox_stateChanged(int arg1){
                                                         ^
gradientdialog.cpp:174:98: warning: unused parameter 'previous' [-Wunused-parameter]
void GradientDialog::on_presetList_currentItemChanged(QListWidgetItem *current, QListWidgetItem *previous){
                                                                                                 ^
gradientdialog.cpp:240:54: warning: unused parameter 'arg1' [-Wunused-parameter]
void GradientDialog::on_stopOpacity_valueChanged(int arg1){
                                                     ^
5 warnings generated.
In file included from kbmode.cpp:1:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from kb.cpp:6:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
rlistwidget.cpp:54:43: warning: unused parameter 'item' [-Wunused-parameter]
void RListWidget::change(QListWidgetItem* item){
                                          ^
1 warning generated.
In file included from kbprofiledialog.cpp:2:
In file included from ./kbprofiledialog.h:5:
In file included from ./kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
kbprofiledialog.cpp:39:100: warning: unused parameter 'previous' [-Wunused-parameter]
void KbProfileDialog::on_profileList_currentItemChanged(QListWidgetItem *current, QListWidgetItem *previous){
                                                                                                   ^
In file included from keywidget.cpp:7:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from kbbindwidget.cpp:2:
In file included from ./kbbindwidget.h:5:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
3 warnings generated.
2 warnings generated.
In file included from kbbind.cpp:4:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from rebindwidget.cpp:2:
In file included from ./rebindwidget.h:5:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from modeselectdialog.cpp:1:
In file included from ./modeselectdialog.h:5:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
rebindwidget.cpp:850:48: warning: unused parameter 'checked' [-Wunused-parameter]
void RebindWidget::on_rb_delay_no_toggled(bool checked)
                                               ^
rebindwidget.cpp:862:53: warning: unused parameter 'checked' [-Wunused-parameter]
void RebindWidget::on_rb_delay_asTyped_toggled(bool checked)
                                                    ^
rebindwidget.cpp:873:53: warning: unused parameter 'checked' [-Wunused-parameter]
void RebindWidget::on_rb_delay_default_toggled(bool checked)
                                                    ^
2 warnings generated.
5 warnings generated.
In file included from kbfirmware.cpp:1:
In file included from ./kbfirmware.h:4:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from fwupgradedialog.cpp:3:
In file included from ./fwupgradedialog.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from kbperf.cpp:2:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
kbperf.cpp:330:27: warning: comparison of constant 8 with expression of type 'KbPerf::indicator' is always false [-Wtautological-constant-out-of-range-compare]
    if(index < 0 || index >= I_COUNT)
                    ~~~~~ ^  ~~~~~~~
kbperf.cpp:345:27: warning: comparison of constant 8 with expression of type 'KbPerf::indicator' is always false [-Wtautological-constant-out-of-range-compare]
    if(index < 0 || index >= I_COUNT)
                    ~~~~~ ^  ~~~~~~~
2 warnings generated.
2 warnings generated.
4 warnings generated.
In file included from keyaction.cpp:2:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from mperfwidget.cpp:1:
In file included from ./mperfwidget.h:11:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from kperfwidget.cpp:1:
In file included from ./kperfwidget.h:9:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
mperfwidget.cpp:81:36: warning: unused parameter 'index' [-Wunused-parameter]
void MPerfWidget::colorClicked(int index){
                                   ^
In file included from layoutdialog.cpp:2:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
3 warnings generated.
2 warnings generated.
In file included from extrasettingswidget.cpp:3:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from kbmanager.cpp:1:
In file included from ./kbmanager.h:8:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from release/moc_mainwindow.cpp:9:
In file included from release/../mainwindow.h:9:
In file included from ./kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_kbwidget.cpp:9:
In file included from release/../kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from release/moc_kbprofile.cpp:9:
In file included from release/../kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_kbmode.cpp:9:
In file included from release/../kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_kb.cpp:9:
In file included from release/../kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_kbprofiledialog.cpp:9:
In file included from release/../kbprofiledialog.h:5:
In file included from ./kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_kbbindwidget.cpp:9:
In file included from release/../kbbindwidget.h:5:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_kbbind.cpp:9:
In file included from release/../kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from release/moc_rebindwidget.cpp:9:
In file included from release/../rebindwidget.h:5:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_modeselectdialog.cpp:9:
In file included from release/../modeselectdialog.h:5:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from release/moc_kbfirmware.cpp:9:
In file included from release/../kbfirmware.h:4:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_fwupgradedialog.cpp:9:
In file included from release/../fwupgradedialog.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_keyaction.cpp:9:
release/../keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
release/../keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from release/moc_mperfwidget.cpp:9:
In file included from release/../mperfwidget.h:11:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_kperfwidget.cpp:9:
In file included from release/../kperfwidget.h:9:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from release/moc_kbmanager.cpp:9:
In file included from release/../kbmanager.h:8:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.

After looking through the script again when running it, it seems to be more than 2 warnings. Sorry again for not being competent with computers, and thanks for your help so far!

**Comment by SethBarberee** [comment]
If `quickinstall` failed, try [this](https://github.com/ccMSC/ckb/blob/master/BUILD.md#osx). If that fails too, then we know that it's a problem in the code which I would hope that it isn't. I think it's something that went wrong in building because I have the same device in Linux and it works perfectly

**Comment by mgw1214** [comment]
When trying to build through Qt Creator, I get the error found in this thread: https://github.com/mattanger/ckb-next/issues/232

I don't think there's an active solution to that problem yet. This is the version of Qt Creator I'm running:
Qt Creator 4.3.1
Based on Qt 5.9.1 (Clang 7.0 (Apple), 64 bit)

Would it help if I directly installed the offline installer of Qt 5.9.1?

**Comment by ghost** [comment]
No, it wouldn't. There's no known way to compile the software under macOS anyhow so far. Hopefully CMake will be introduced soon.

_Sent from my LeEco Le X820 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mgw1214** [comment]
Alright thank you all for the help! Unfortunately it looks like I'll be returning the Scimitar until there's a way to run it on a Mac.

**Comment by tatokis** [comment]
Have you tried https://github.com/mattanger/ckb-next/releases/download/v0.2.8/ckb-v0.2.8.pkg ?
It should have support for the scimitar there
