### ISSUE TITLE
Scimitar RGB Left click stops working for a few seconds randomly.

### ISSUE THREAD

**Issue by alkanna** [mattanger/ckb-next#258]
I am using the last pkg release on Sierra.
For some reason it looks like the left click gets stuck on hold or something for a few seconds, randomly, every 20 seconds or so. Changing the active window seems to trigger this bug more frequently. Sometimes I can even select text like usual on chrome, but I can't change tab or click anything on a page. Right click and all other mouse bindings works fine while this happens. It's only a left click issue.

I tried saving my setup to hardware, uninstalling ckb and restarting my computer but then my bindings just disappear. It doesn't seem like the save to hardware function is working.

If I click and drag while left click is not clicking properly, I usually move some stuff around where I last tried to click. For example on chrome, left click would stop working, I try to select some text and then it starts moving the tab. When I release left click the tab would be a new window.

Also I used to be able in World of Warcraft with another mouse to hold right click and it would let me move the camera around like it's supposed to, and it would basically hide the cursor while doing it. It does so with the scimitar, except the cursor quickly goes on the edge of the window and cannot go further, thus preventing me from being able to continue moving the camera in that direction. It forces me to bring back the cursor in the middle of the screen to be able to start moving the camera again in said direction. With my RAT5 it natively just hides the cursor but does not move it in the background while holding right click and moving the camera.

Anyone else experiencing this ?

Unless this is a known bug it looks like I'm going to return it. There are just too much issues sadly.

**Comment by OscarBarrett** [comment]
When it occurs, have you tried restarting the daemon to fix it?

It sounds like the mouse is sticking a bit when you click and hold left click? If so, you may be experiencing https://github.com/mattanger/ckb-next/issues/93

**Comment by alkanna** [comment]
Restarting the daemon does not help because the issue appears and stays for a few seconds only, then goes back to normal.

My mouse never gets stuck in one coordinate though, the left click gets stuck,  but only sometimes.

**Comment by alkanna** [comment]
Any updates on this ?

**Comment by OscarBarrett** [comment]
I'm using a Scimitar RGB on Sierra and have never had this issue. If you can find a way to reproduce it I'd be happy to test.

**Comment by alkanna** [comment]
Are you using the last pkg release or did you build it yourself ?
It just happens, mostly when playing World of Warcraft. I can't really force it to happen.

**Comment by alkanna** [comment]
The mouse is working fine when ckb isn't running or for example now that I restarted for some reason it says no devices connected, the mouse works fine. However I cannot configure any of the additional buttons on it.

**Comment by alkanna** [comment]
Alright I managed to narrow it down a bit more : What happens is that when I select a window/tab then want to quickly select another, like select a tab in chrome then another one in the next second, it doesn't click it. If I let the mouse hover on the other tab for a second or more, then click it, it works as intended.

EDIT : It seems it had something to do with the double click speed setting from OSX, will test it some more and get back to you with more info ! Seems like the RAT5 driver I was using was overwriting this setting because I never had the issue.

**Comment by alkanna** [comment]
Alright I'm closing this issue, what I said above basically resolved it, but I still have a problem with the mouse not snapping to the window like it should in WoW.
