### ISSUE TITLE
Strafe RGB Keyboard not being detected by computer at all

### ISSUE THREAD

**Issue by Dplm1** [mattanger/ckb-next#260]
Hello. when i originally purchased my Strafe RGB keyboard, I installed ckb beforehand. The keyboard was successfully recognized and functioned with keyboard functions and RGB effects for about 2 days. The morning of the third day the keyboard is suddenly unresponsive and displays a random preset of colors once every 30 seconds or so. Ever since then I've been having issues with having my computer recognizing the keyboard. The keyboard lights up when I plug it in, but only with built in presets. Keyboard keys do not work, but the usb pass through does work. I've been using the binary download, so I'm not so used to all the code needed for the other way to install ckb. I will use the other way of installation if necessary though. I'm using an iMac running OS X El Capitan version 10.11.6. The device does not show up in the usb category of system report. Thank you for taking the time to read this.

**Comment by ghost** [comment]
> __Problem__: Keyboard isn't detected when plugged in, even if driver is already running
__Solution__: Try moving to a different USB port. Be sure to follow [Corsair's USB connection requirements](http://forum.corsair.com/v3/showthread.php?t=132322). Note that the keyboard does not work with some USB3 controllers - if you have problems with USB3 ports, try USB2 instead. If you have any USB hubs on hand, try those as well. You may also have success sliding the poll switch back and forth a few times.

I suppose you are aware of the requirements and read our README.

First of all, if your keyboard does not work and you have fulfilled the requirements, unload the daemon

```
sudo unload /Library/LaunchDaemons/com.ckb.daemon.plist
```

and replug the keyboard (multiple times) with some time delta, for example 10 seconds. Strafe RGB must work without any daemons.

Make sure the keyboard functions normally, e.g. you can type consistently.
* If it does, install ckb-next. If you will have issues with ckb-next, create an issue and fill in the template with the description your problem, it was written for a reason.
* If you cannot type consistently, I suppose there's nothing we can help you with.
