### ISSUE TITLE
Keeps crashing!

### ISSUE THREAD

**Issue by liamgoggin** [mattanger/ckb-next#276]
Everytime I try to open the app it crashes. I have tried re-installing it multiple times and restarting my macbook however it continues to crash.

**Comment by liamgoggin** [comment]
I have since re-downloaded it another time and for a second before it crashed it would show a little preview of my devices showing that they are actually recognised which is an improvement. However it still continues to regularly crash. I have a K70 rgb lux keyboard and the sabre rgb mouse and I use the 11" macbook air 2015 model.

**Comment by ghost** [comment]
I would recommend you to open a new issue, but this time reading the issue template and filling it out. You have literally provided zero information to work with.
