### ISSUE TITLE
K55 RGB support

### ISSUE THREAD

**Issue by DGxInfinitY** [mattanger/ckb-next#277]
I just got both and was wondering if I could maybe help in development and what plans are in the works for these pieces of kit.

**Comment by tatokis** [comment]
The harpoon is already supported, have to get the code from the newdev branch.
Regarding the K55, please run ckb-dev-detect and attach it.

**Comment by DGxInfinitY** [comment]
@tatokis 
How can I run ckb-dev-detect, I am on Linux and have compiled but I see no executable in the bin directory...
Edit I ran ckb-dev-detect and I was able to find all input devices, I am going to attach it here:
[[ckb-dev-detect-report.gz](https://github.com/mattanger/ckb-next/files/1229535/ckb-dev-detect-report.gz)]
Also, I am getting no devices detected with Harpoon Mouse, how would I go about fixing that?

**Comment by DGxInfinitY** [comment]
Also, I am getting no devices detected with Harpoon Mouse...

**Comment by ghost** [comment]
IIRC @SethBarberee was working on K55. I guess we should turn this into a K55 thread, since we don't have one yet.

**Comment by SethBarberee** [comment]
I actually was just thinking out loud on how to implement support. I don't have a K55 to test with any code that I would write.

**Comment by DGxInfinitY** [comment]
Alright I got the harpoon to work after compiling the newdev branch like you said. It seems to be glitchy but at least it works. 
Back to the K55
I have no idea on how I can help, what development libraries I need or other so if someone could fill me in I would love to be if assistance. Thanks guys you are so quick to help it's quite refreshing to see a couple of great devs!

**Comment by DGxInfinitY** [comment]
BTW I do have the K55 in hand so I can test the code you write.

**Comment by tatokis** [comment]
Yeah, not quite sure how this is implemented.
I'll add it as a new device soon, and we can experiment and see if we can get any of the lights to work.

**Comment by tatokis** [comment]
@DGxInfinitY Does the K55 even work with the CUE software? If not, there's not much we can do about it.

**Comment by DGxInfinitY** [comment]
Just looked it up and it appears not but it does use function keys so if there is a way to send out keystrokes to the keyboard we could control the keyboard through specific key combos. We will have to look into the actual keyboard logic board, I don't know why they don't keep everything simple with these things, it actually complicates manufacturing for them...
![img_20170821_145532](https://user-images.githubusercontent.com/10894088/29538139-9d149586-8681-11e7-831e-744544c98381.jpg)

**Comment by tatokis** [comment]
Yeah, there is no official way to control this keyboard from software.

It might be possible with some modifications, or undocumented instructions, as it does have the required endpoints, however this is out of scope for this project.

If anyone ever figures it out, or adds support, feel free to open a PR.
Until then there is nothing we can do.

**Comment by tatokis** [comment]
Apparently control through CUE is possible, reopening.
Anyone who runs Linux and is interested in spending a good few hours on this, feel free to join our IRC room (at sensible EU times).

**Comment by ghost** [comment]
I am willing to help. As I myself, have an ArchLinux and a K55 RGB Corsair Keyboard. (all I want to do is to be able to use the RGB lights of the keyboard from time to time. Haha.) CKB is not detecting K55 RGB Corsair keyboard. I am willing to spend as long as it takes. To go to a windows computer and save the output info of K55 RGB code, and back into my ArchLinux.. etc... Pacific Time -8. Let me know. Peace be upon You all. :)

**Comment by Ravenslofty** [comment]
I have a branch which detects and connects to the K55. At the moment lighting does not work. We're taking a break for the holidays, so don't expect significant progress for a while.

**Comment by ghost** [comment]
Of course. Rest well. Well if there is anyway I can contribute to helping the linux community code for K55 RGB, then I will be willing. My keyboard is always detected via Arch but not CKB and I would love to help the RGB light button work for the linux community and myself.

**Comment by Barrosv1** [comment]
New here and to programming, with a k55 willing to help if needed. Would like to get my k55 running on my mac with ckb.

**Comment by tatokis** [comment]
Sorry, my mistake for not posting here. There is some K55 support now that has only been tested on linux. You can get the code from #362.
@Barrosv1 if you would like, compile the code from that branch/PR, instructions on how to do that on macOS are in the readme. If it doesn't work on macOS, please do post the log/output of ckb-daemon.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/30
