### ISSUE TITLE
Keeps opening and closing.

### ISSUE THREAD

**Issue by Moltqn** [mattanger/ckb-next#285]
I recently installed ckb-next because I wanted to change my K70 lighting. So I opened the application and it closed. After that I thought I just needed to restart my laptop, so I did and the problem continued but I never opened the application myself, it just kept opening and closing itself. I'm running on macOS Sierra 10.12.5 and my keyboard is the K70 Rapidfire if that helps.

**Comment by ghost** [comment]
> if that helps

It would have helped if you had read and filled out the issue template instead of ignoring it.

There is some problem with your user configuration. Try the `.pkg` at the end of #281.
