### ISSUE TITLE
Binding animation to a key should also send that key to the app [Feature request]

### ISSUE THREAD

**Issue by Extarys** [mattanger/ckb-next#291]
# Feature request
- [x] Yes

## What is the program's current behavior?
Tab "Binding" -> Animation -> Start animation on keypress
The animation is played but the key is not triggered.
Exemple:
I assigned an animation to a letter "R". The animation is played when I press it but on the address bar I don't see the R.

Those are radio button so when selecting animation the key binding for "keyboard" R" disappear. It isn't probably not implemented too so...

## What would you like it to do instead?
Add the possibility to play an animation when a specific key is pressed and print the key.
Exemple: I assigned R to an animation called Ultimate that bring the keyboard red. It should also send that I pressed R to the program or game.

## Any other notes & comments?

Maybe it's there somewhere but I didn't find it. It would be nice for MOBA (League of Legend and Heroes of the Storm)

Thanks!

---
### Branch
**newdev**

(BTW I will buy the glaive too, thansk for the awesome driver!! <3)

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/34
