### ISSUE TITLE
Add Spectrograph as a possible animation

### ISSUE THREAD

**Issue by Extarys** [mattanger/ckb-next#292]
# Devices information
K70 LUX RGB

# Feature request

- [x] Yes

## Any other notes & comments?

Would be cool to include the Spectrograph from [CalcProgrammer1/CorsairKeyboardSpectrograph
](https://github.com/CalcProgrammer1/CorsairKeyboardSpectrograph) in the animations

**Comment by tatokis** [comment]
While a bit buggy, have you looked at mviz? (#143)

**Comment by Extarys** [comment]
Ouch thanks, sorry for the duplicate, I looked I swear :P
It's mainly for fun though.
