### ISSUE TITLE
Qmake vs. Cmake?

### ISSUE THREAD

**Issue by JarrenJ** [mattanger/ckb-next#293]
So....
I am using an older qmake version. I recently revisited this thread and found out there is now a lot of talk about cmake. I am using the latest version of macOS and I need to update my CKB. Last time I did this though it took me about a day and a half to get it to recognize my devices. 

~~ My question is: **Would Cmake be better than Qmake for me, or no?**

My current problem is when ever i shut down or restart my MAC I need to do it about 3 or 4 more times until it recognizes my devices. Any suggestions would be greatly appreciated.

Thanks, JarrenJ.

**Comment by ghost** [comment]
> My question is: Would Cmake be better than Qmake for me, or no?

No, for the end user there will be almost no differences. For more powerful users additional compilation and installation options will appear, which doesn't alter the end products. CMake transition is supposed to create a certain ecosystem to allow faster, feature-rich and more comfortable development.

CMake is the future, qmake is the legacy.

Also, you might want to test CMake PR to find possible issues.

> My current problem

If you experience some certain problem, open an issue describing it.
