### ISSUE TITLE
Unable to change DPI when DPI on specific stage concides with Sniper DPI

### ISSUE THREAD

**Issue by nazar-pc** [mattanger/ckb-next#298]
[ckb-dev-detect-report.gz](https://github.com/mattanger/ckb-next/files/1313139/ckb-dev-detect-report.gz)
# Bug report

- [x] Yes
- [ ] No

### Source
Manually build from `master` branch as of right now: https://github.com/mattanger/ckb-next/commit/d65d782f8595fd90316a19df1607f1267e013d6e

## What is the program's current behavior?
When DPI level coincides with Sniper DPI I can't change DPI with Up/Down buttons anymore.

## What is the expected behavior of the program?
DPI Stages should not stuck when coincide with Sniper.

## Any other notes & comments?
For instance, this happens when Sniper DPI is 500 and DPI Stage 1 is also 500. Changing DPI Stage 1 to 501 fixes the issue.

**Comment by pjcv** [comment]
Please take a look at https://github.com/pjcv/ckb-next/tree/dpistack (branched from newdev).

**Comment by nazar-pc** [comment]
Doesn't help unfortunately.
Here are my settings:
![2017-09-19 20-40-33](https://user-images.githubusercontent.com/928965/30606576-d888076e-9d7a-11e7-8e12-b9482f38768c.png)

**Comment by pjcv** [comment]
Using those settings I can reproduce your issue on newdev but not on my branch... what are your bindings?

**Comment by nazar-pc** [comment]
Attached complete config (except Stage 1 speed set to 450 for now)
[ckb.conf.gz](https://github.com/mattanger/ckb-next/files/1315319/ckb.conf.gz)

**Comment by pjcv** [comment]
Thanks. I'm not able to use your settings exactly on my Glaive, but with something very similar (binding the mode-switch to the right mouse button) I'm able to reproduce the issue on newdev but not on my branch.

**Comment by nazar-pc** [comment]
Maybe there is someone else with M65 Pro RGB to try?

**Comment by pjcv** [comment]
Agreed it would be nice to have some other people try this, we could use some more data here. I was able to reproduce and fix at least one cause of this issue, so it seems there must be some other factor in play.

**Comment by pjcv** [comment]
I made one further change which _might_ affect you, @nazar-pc:
https://github.com/pjcv/ckb-next/commit/2d5b628c97ba97ab3d9af7cc9dacf9913fe09306
This should prevent the sniper DPI from being assigned on startup, though in my case, I was still able to change DPI after this.  If you have a chance please give it another try.

**Comment by nazar-pc** [comment]
Compiled from mentioned commit and it now works correctly!

**Comment by pjcv** [comment]
Great! Thanks for your patience. I'll put together a PR.
