### ISSUE TITLE
Single Spot Heat Map Issue

### ISSUE THREAD

**Issue by slugger7** [mattanger/ckb-next#30]
Where as I type sometimes some keys will keep on doing the heat map effect on certain keys.
I had this issue with the newdev branch on the original CKB as well (i have the K70 LUX).
Is my settings by any chance wrong for the heatmap to work properly?
[Here](https://drive.google.com/open?id=0B2hUGYneQmLuTElGSHJGZWtHdXc) is a video demonstrating what is happening.
It does it on random keys at random intervals

**Comment by tatokis** [comment]
If I understood correctly, that is the intended use of a heat map.
The point of it is to keep the most used keys lit.

If you just want the keys to light up as you type and then fade out, you can use Gradient -> Type lighting.

**Comment by tatokis** [comment]
Apologies, I set a black background and I can see the keys randomly starting to light up for no reason.
I'll have a look in the code and see what is going on.

**Comment by tatokis** [comment]
Please try the latest HEAD from the testing branch.
The issue should be fixed.

**Comment by slugger7** [comment]
Just got time to get to testing it. Will keep you posted if I find any issues with the type lighting

**Comment by slugger7** [comment]
@tatokis it seems to have fixed the problem. Thank you very much

**Comment by tatokis** [comment]
Awesome!
