### ISSUE TITLE
Corsair Scimitar Pro Issue

### ISSUE THREAD

**Issue by Sankhai** [mattanger/ckb-next#307]
Hi all,
Everything seem to be working fine with the app but the left click seems broken.
Sometimes I just can't click something, like there's no left click at all but then it works on something else. (F.E. I click on a TAB in google chrome, it works, then I try an another TAB : it won't ever load.)

It may sound stupid but it's completely impossible to use the mouse like that.
As anyone experienced this once?

Thank you in advance for your tips. 

_**Sankhai**
MBP 15" Late 2014
Graphic Designer_

PS: The left click is correctly assigned. 
<img width="995" alt="capture d ecran 2017-10-03 a 13 32 41" src="https://user-images.githubusercontent.com/31647117/31123302-a025ecd6-a83f-11e7-83a5-a4ca723f7cf2.png">

**Comment by ghost** [comment]
Can you reproduce this behaviour without `ckb-daemon` running?
 
You can disable it with `sudo launchctl unload -w /Library/LaunchDaemons/com.ckb.daemon.plist`.

**Comment by Sankhai** [comment]
I just tried it and unfortunately now ckb just won't detect the mouse no matter what I try (plug/unplug/reboot) :( 
Thank you for trying to help!

<img width="992" alt="capture d ecran 2017-10-04 a 10 45 35" src="https://user-images.githubusercontent.com/31647117/31167188-79ad613a-a8f1-11e7-84f5-f1873cfcb35f.png">

**Comment by valkayrie** [comment]
Have you tried assigning left click to another button? Just to make sure it's not a software issue.

To rule out a hardware problem, does left click work on other computers/OSs? Or try assigning a different function to M1 and try that.

**Comment by Sankhai** [comment]
Woaw I've finally figured out what was the problem.
#258 Topic helped me a lot. 
Seems like it's actually the MacOS Sierra "double-click speed" that stucks the left click.
Resolved it by putting the sensor a bit higher than mid range.
Closing the topic, thank you all.

**Comment by ghost** [comment]
@Sankhai thanks for sharing the solution, this is something to consider when dealing with mice issues on macOS.
