### ISSUE TITLE
Add "Alt Gr" (right alt) modifier key

### ISSUE THREAD

**Issue by mgcrea** [mattanger/ckb-next#318]
Would be great to be able to change the `alt` key and `alt gr` (right alt) independently.

In my case, I want the alt key to be mapped to the command key but I need the right alt key to remain an alt key (for curly braces, etc.).

Thanks!

**Comment by tatokis** [comment]
Would you mind explaining a bit more? I am really confused as to what the problem is. If you remap the left alt, the right one should not be affected.

**Comment by mgcrea** [comment]
In my case, with a Corsair Strafe RGB, changing the Alt key does also changes the Right Alt key, any log I could dump to help you?

**Comment by tatokis** [comment]
CC @light2yellow 
Can you check this for me?

**Comment by ghost** [comment]
@tatokis 

Can't "repro" on `0.2.8.r229.gc7ed718`, Linux `4.14.2`, fw `3.05`.

@mgcrea 

Elaborate on what exactly you've tried, with what program version you've tried, on what OS you've tried, and so on. Ignoring the issue template is not going to help in solving your issue.

Either way, what I did:
* Remapped LAlt -> 1, RAlt untouched, both act as expected
* Remapped RAlt -> 1, LAlt back to LAlt, both act as expected

Is it one issue or multiple ones? In the first message you mention AltGr - I think we don't support it at the moment. Then you say that when you remap one Alt, the other one remaps too. Are these issues connected?

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/39
