### ISSUE TITLE
Can't build on solus

### ISSUE THREAD

**Issue by QuillzLouis** [mattanger/ckb-next#321]
Trying to build on solus, failing. I have installed the system.devel package and qt5-base-devel/
[ckb-dev-detect-report.gz](https://github.com/mattanger/ckb-next/files/1424149/ckb-dev-detect-report.gz)

Output from "sudo ./quickinstall": [https://hastebin.com/ajohanohig.tex](https://hastebin.com/ajohanohig.tex)

**Comment by ghost** [comment]
Udev is required. It is a part of systemd now. If systemd is not available, you can try eudev.

**Comment by QuillzLouis** [comment]
@light2yellow I've installed libudev and libudev-devel and I'm getting this error now when building https://hastebin.com/okonehixiz.tex

**Comment by ghost** [comment]
As you can see, the error hasn't changed. `libudev.h` is not found in the standard search path for headers. `gcc -v -E -` shows the directories where GCC expects to find it.

**Comment by QuillzLouis** [comment]
@light2yellow 
I've now got past the libudev error and have got this error:
> Install ckb system-wide [Y/n]? y
> sudo: pam_open_session: System error
> sudo: policy plugin failed session initialization

Full output: https://hastebin.com/gecogewevo.tex

**Comment by ghost** [comment]
I have no idea how your OS approaches permission granting. `ckb-next` supports Linux and macOS. So, you are pretty much on your own. Patches are welcome.

**Comment by QuillzLouis** [comment]
@light2yellow solus is a linux distro.

**Comment by tatokis** [comment]
@QuillzLouis is sudo working at all?

**Comment by tatokis** [comment]
@QuillzLouis Actually. stupid question. You mentioned you ran sudo ./quickinstall.
I haven't attempted it, but I am sure quickinstall needs to run as a normal user. The script itself asks for root access when it needs it.

**Comment by ghost** [comment]
> solus is a linux distro

Ah, okay. From the first glance it seemed it's something else. Moreover, I was amused to see it on number 8 on distrowatch...

Anyway, what @tatokis said.

**Comment by QuillzLouis** [comment]
@tatokis @light2yellow The output when running ./quickinstall without root 
https://hastebin.com/raw/osavefujad

**Comment by ghost** [comment]
Well, that is expected. Try
```
sudo make clean
./quickinstall
```
