### ISSUE TITLE
Suggestion on a Light Management only version.

### ISSUE THREAD

**Issue by owenzhao** [mattanger/ckb-next#323]
My K65 RGB works perfectly with Karabiner-Elements on macOS High Sierra 10.13. F1-F12 Key works the same as a Magic Keyboard. The only existing issue is the light part.

Maybe you can use release a ckb-next just for the light management. I used to use CapsLock key to switch the light of A-Z. Now that is the only needs from ckb-next.

**Comment by ghost** [comment]
@owenzhao Are you not having modifier key issues, ie... Shift, CTRL being able to select multiple files, folders?

**Comment by owenzhao** [comment]
@brockbackups On which app? Just tested on Karabiner-Elements, no issue.

**Comment by ghost** [comment]
@owenzhao my bad I thought you was talking about ckb-next, sorry for the misunderstanding

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/41
