### ISSUE TITLE
K70 LUX firmware upgrade 2.05 fails

### ISSUE THREAD

**Issue by berolinux** [mattanger/ckb-next#328]
The CKB UI shows that a firmware upgrade from 2.04 to 2.05 is available.
Trying to install it brings up the "Ready to install new firmware." dialog, but says "Update failed." immediately after clicking "Start".

**Comment by tatokis** [comment]
There is no 2.05 for the LUX. This is an old bug, with a fix that on a PR that we never merged due to the fact that the branch it was based against has been removed.
Thanks for the reminder.

https://github.com/mattanger/ckb-next/pull/220
#97
