### ISSUE TITLE
Mouse pointer moving position with camera movement

### ISSUE THREAD

**Issue by Trololui** [mattanger/ckb-next#329]
In games like "World Of Warcraft" when you click and hold to move the camera, normally the pointer disappears and stays at the position where you clicked.... for some reason with the software installed the pointer disappears but it moves when you are moving the camera so when you finish the camera movement the pointer is in a new position.

WIthout the software, it works as expected.

If you need any more info, please let me know.

**Comment by avnonline** [comment]
I'm also seeing this behavior, the mouse swings to the very top left and corner and gets locked to that position.
