### ISSUE TITLE
K95 Platinum Firmware Update 2.05

### ISSUE THREAD

**Issue by shoxter** [mattanger/ckb-next#332]
So far, this package works very well. However, whenever I open the GUI interface, it asks me if I want to update the firmware of my keyboard to 2.05 (from 1.07). After pressing "Start," it says "Update Failed" immediately after.

Am I doing something wrong?

Thank you in advance.

**Comment by tatokis** [comment]
There is no such update, this is a bug in the software. Untick check for updates checkbox and it won't bug you again. There are multiple issues about this on the bug tracker.
