### ISSUE TITLE
CUE is coming to macOS

### ISSUE THREAD

**Issue by mhennessie** [mattanger/ckb-next#335]
This isn't an issue, but CUE is coming to macOS shortly. I am currently running a beta of it and it works great so far. It has all of the features of the Windows variant and maintains the complete look and feel. It is working perfectly with my K65 RGB and M65 Pro RGB while running macOS 10.13.1.

![CUE for macOS](https://i.imgur.com/6XoxEE9.jpg)

**Comment by fleischie** [comment]
@mhennessie Is there any publicly available information on this topic/beta? Are you referring to http://forum.corsair.com/v3/showthread.php?t=168738 ?

**Comment by tatokis** [comment]
Corsair has money to spend for kernel drivers. We do not, so we have to deal with tons of hacks and workarounds.
I'm sorry but this is completely unrelated to the project.

**Comment by mhennessie** [comment]
@fleischie yes that is the topic.

**Comment by mhennessie** [comment]
@tatokis how is this unrelated? This project only exist because CUE and drivers for macOS did not. Full support for our devices is coming which is great news.

**Comment by tatokis** [comment]
@mhennessie this is a bug tracker for issues related to this project, and this is not an issue.
The software is not exclusive to mac either. This project will still exist after this.

**Comment by JarrenJ** [comment]
@mhennessie I have a question for you if you could reply to me here or by email at j.jarren@yahoo.com. I would appreciate it, thanks.

**Comment by mhennessie** [comment]
@jarrenj what’s your question?

**Comment by JarrenJ** [comment]
@mhennessie so I contacted James from the forum post and he gave me the files I need. However when I try to update to Frimware 3.x.x on my Windows machine, its says it is an invalid Firmware... Could you maybe tell me what I'm doing wrong? I got the firmware .zip for both my devices and when I upload the firmware image it says Invalid... any ideas?

**Comment by mhennessie** [comment]
@jarrenj which file are you using? The zipped firmware files I downloaded contained a few files. Also make sure you have downloaded the files for the correct device.

**Comment by JarrenJ** [comment]
@mhennessie so I am doing my Scimitar Pro first. I downloaded that .zip and it contained 3 .bin files. I then chose to upload the .zip file to my device through CUE. correct?

**Comment by mhennessie** [comment]
@jarrenj you don’t upload the whole zip file. You will upload only one of them. I used the one with APP in the name.

**Comment by JarrenJ** [comment]
@mhennessie ok thanks, Ill try that when I get back home. Thanks for the help!
