### ISSUE TITLE
Strafe RGB macros set vol up/down randomly

### ISSUE THREAD

**Issue by ghost** [mattanger/ckb-next#336]
I'm on Fedora 26, ckb-next v0.2.8, Strafe RGB (2.05 fw) + M65 Pro RGB (2.06 fw). Systems and firmwares are all updated. Sometimes, after I use a macro, when I press almost every key, it prints itself and sets volume up/down randomly more then one time per second, so keyboard and volume become uncontrollable. Does Strafe RGB have a controllable BIOS mode (the keyboard does not have any front / back key for bios mode)? Is this a bug?

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/43
