### ISSUE TITLE
Issue with System Intermittent Freezes / Lockups after pressing CAPS LOCK Button

### ISSUE THREAD

**Issue by Handsomfreddy** [mattanger/ckb-next#337]
Can someone provide a new Mac .pkg file for download with the latest changes to the master branch?  It would be greatly appreciated.

**Comment by JarrenJ** [comment]
@Handsomfreddy I found a workaround for he CAPS LOCK button a long time ago. Check for issues with me in it, I think it should pop up. As for the .pkg file. Why not just build from Source by running the ./quickinstall script?

**Comment by JarrenJ** [comment]
https://github.com/mattanger/ckb-next/issues/23#issuecomment-275820468 

That is my comment stating the workaround, if that is the same problem you are having.

**Comment by Handsomfreddy** [comment]
Thanks Jarren, I’ll give it a go.  Don’t I need xcode to do the build from source?

**Comment by JarrenJ** [comment]
I believe you need x-code yes... but I can’t rememeber. It might just be QT that you need.
