### ISSUE TITLE
Volume controls not working in Ubuntu 17.10

### ISSUE THREAD

**Issue by Alan-Penkar** [mattanger/ckb-next#339]
# Bug report

- [ X] Yes
- [ ] No

<sub><sup>leave empty if you have no bug reports</sup></sub>

### Source
I built this manually using the quickinstall script

### Branch
master

## Logs & crash reports

You should upload:
- Linux: `ckb-dev-detect-report.gz` is enough
- macOS:
    * the output of `ckb-daemon`:
    ```console
    $ sudo launchctl unload /Library/LaunchDaemons/com.ckb.daemon.plist
    $ sudo /Applications/ckb.app/Contents/Resources/ckb-daemon
    ```
    * the output of `ckb` (open another terminal):
    ```console
    $ sudo killall -9 ckb
    $ /Applications/ckb.app/Contents/MacOS/ckb
    ```

## What is the program's current behavior?
The volume up/down and mute keys do not do anything.
## What is the expected behavior of the program?
The volume roller and mute key will control the volume
## Any other notes & comments?
-
[ckb-dev-detect.zip](https://github.com/mattanger/ckb-next/files/1468756/ckb-dev-detect.zip)
[ckb-dev-detect.zip](https://github.com/mattanger/ckb-next/files/1468762/ckb-dev-detect.zip)

---

# Something else

<sub><sup>if your issue is about something else, try your best to describe it here, otherwise leave empty</sup></sub>

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/44
