### ISSUE TITLE
Caps Lock won't unlock from Corsair K65 RGB

### ISSUE THREAD

**Issue by Donzap** [mattanger/ckb-next#340]
MacOS Sierra v10.12.6
Last ckb-next binary download
Corsair K65 RGB
Corsair M65 PRO RGB
Macbook Pro 15" Touch Bar

Lighting and remapping works like charm, actually some weird stuff when changing active window or hitting interface buttons in mac, don't know if really an issue or is something like a placebo effect since I recently installed ckb-next, I will investigate further.

Hitting Caps Lock on K65 turns on caps lock. The keyboard light on the K65 and on the mac keyboard both turn on. Pressing caps lock further in K65 won't turn caps lock off however. But pressing it on mac's keyboard will turn caps lock off but not the light in K65. Is like a two point room light switch with bad wiring.

Exact like in #158 but they didn't really know how they fix it.

Thank you!

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/45
