### ISSUE TITLE
Mouse unresponsive after suspend/resume cycle

### ISSUE THREAD

**Issue by taisph** [mattanger/ckb-next#341]
# Bug report

- [x] Yes
- [ ] No

### Source

Built from git master ref v0.2.8-224-gb88d8be.

### Branch

master

## Logs & crash reports

Attached.

## What is the program's current behavior?

Mouse is unresponsive after reboot if ckb was running. Animations are still playing on mouse. I have to run `ckb --close` and `systemctl restart ckb-daemon` before mouse can be used again.

## What is the expected behavior of the program?

Mouse is responsive.

## Any other notes & comments?

If `ckb` isn't running when suspending, the mouse works as expected after resuming, so it seems `ckb` may be preventing `ckb-daemon` from handling suspends correctly.

**Comment by taisph** [comment]
[ckb-dev-detect-report.gz](https://github.com/mattanger/ckb-next/files/1495154/ckb-dev-detect-report.gz)

**Comment by Ravenslofty** [comment]
Just as a quick acknowledgement - I have the exact same mouse as you, so I will start investigating.

**Comment by Ravenslofty** [comment]
Okay, so with my build of this on b88d8be, I can't actually reproduce this. Come visit us at #ckb-next on Freenode, and mention me on there. I'll be happy to help.

**Comment by tatokis** [comment]
https://github.com/mattanger/ckb-next/issues/58
