### ISSUE TITLE
Strafe RGB No longer recognised

### ISSUE THREAD

**Issue by SG420** [mattanger/ckb-next#350]
# Devices information

Run [`ckb-dev-detect`](https://github.com/mattanger/ckb-next/blob/master/ckb-dev-detect) from the root of the source code tree:

```console
$ ./ckb-dev-detect
```

Upload `ckb-dev-detect-report.gz` on GitHub with this issue.

---

# New device support request

- [] Yes
- [x] No

<sub><sup>leave empty if you have no new device support requests</sup></sub>

You should upload:
* __Linux__: `ckb-dev-detect-report.gz` is enough
* __macOS__: a full dump following [the instructions](https://github.com/mattanger/ckb-next/issues/31#issuecomment-285380447)

---

# Feature request

- [ ] Yes
- [x] No

<sub><sup>leave empty if you have no feature requests</sup></sub>

## Any other notes & comments?

---

# Bug report

- [x] Yes
- [ ] No

<sub><sup>leave empty if you have no bug reports</sup></sub>

### Source
(how and where did you get this program, e.g.: _"`ckb-next-git` package in AUR"_ or _"built manually using quickinstall script"_ or _"pkg for macOS"_)

### Branch
(fill in if ckb-next was compiled manually, e.g.: _"master"_ or _"newdev"_)

## Logs & crash reports
(any useful information - an OS crash report, debugger's backtrace, any non-standard way of usage (BIOS mode ...)  etc.)

You should upload:
- Linux: `ckb-dev-detect-report.gz` is enough
- macOS:
    * the output of `ckb-daemon`:
    ```console
    $ sudo launchctl unload /Library/LaunchDaemons/com.ckb.daemon.plist
    $ sudo /Applications/ckb.app/Contents/Resources/ckb-daemon
    ```
    * the output of `ckb` (open another terminal):
    ```console
    $ sudo killall -9 ckb
    $ /Applications/ckb.app/Contents/MacOS/ckb
    ```

## What is the program's current behavior?

STRAFE RGB is not detected by CKB, it only says No devices connected. I have tried on both my laptop and desktop, both running Manjaro. this issue seems to have only appeared after an update. It works fine in Windows 8.1 Embedded Industry Pro with the proprietary CUE driver installed. I have tried all 4 AUR packages and they all have the same behaviour.

# Something else

<sub><sup>if your issue is about something else, try your best to describe it here, otherwise leave empty</sup></sub>
[ckb-dev-detect-report.gz](https://github.com/mattanger/ckb-next/files/1516755/ckb-dev-detect-report.gz)

**Comment by Ravenslofty** [comment]
Did you run `systemctl start ckb-daemon`? It doesn't run by default, because of the Arch packaging guidelines.

**Comment by Nepoxx** [comment]
@ZirconiumX that fixed the "issue" for me, I'd suggest adding that information on the README :)

**Comment by SG420** [comment]
@ZirconiumX That fixed the issue, thanks.

**Comment by Ravenslofty** [comment]
It's in the AUR package:

```sh
_as_service() {
    cat << EOF

You might want to run ckb-daemon as a systemd service:

    systemctl enable ckb-daemon.service
    systemctl start ckb-daemon.service

EOF
}
```

**Comment by ghost** [comment]
@Nepoxx 
> I'd suggest adding that information on the README

I'd suggest reading the output of `pacman`. It displays the message above every time you install and/or update a package. Regarding the rationale, see https://wiki.archlinux.org/index.php/Systemd#Enable_installed_units_by_default. I am not very happy about this, too and even started/enabled the daemon some time ago by default, but people told me it's not something they want and not something Arch Linux packaging guidelines adore.

**Comment by Nepoxx** [comment]
I'm not arguing whether Arch or the Arch way is right or not, I'm just saying that adding this to the readme could prevent issues like these. It's easy to miss the output of pacman/pacaur/yaourt/etc, especially when installing multiple packages.

The UI could also mention that it can't communicate with the daemon? I could PR that, thoughts?

**Comment by Ravenslofty** [comment]
It does. There's a "driver inactive" message, which @fleischie is working on making more obvious.

**Comment by fleischie** [comment]
Yeah, I guess the Readme is at a length, where nobody even bothers to read it for troubleshooting.

@Nepoxx check out my PR #354. If it works, it should open a dialog to inform you about the inactive daemon. 😄
