### ISSUE TITLE
Is this still the correct place to get ckb-next?

### ISSUE THREAD

**Issue by mjones153** [mattanger/ckb-next#352]
Is this still the correct place to get ckb-next? 

After looking at https://groups.google.com/forum/#!topic/ckb-next/L-E8RiKxPFk  and seeing no further update to that post, I figured checking would be best.

Thank you for your time.

**Comment by OvermindDL1** [comment]
Yep, it is quite active here, look at the recent commits as one example.  :-)

**Comment by Ravenslofty** [comment]
Yes, this is still the correct place to get ckb-next. We plan to wait for the domain to expire to see if *that* gets @mattanger's attention. But for now, we're not going anywhere.

**Comment by OvermindDL1** [comment]
Well if you do set up a new site I have servers available if you don't want just a simple github-pages static site.

**Comment by Ravenslofty** [comment]
Thank you, but no thank you. If we gave you the website, then you disappeared, we'd be in the same situation.

**Comment by tatokis** [comment]
@mjones153 That is mostly used for announcements, next one will probably be for our next release (which is going to be a big one). Either way, as it has been mentioned, we are still here for the moment, but even if we were to move, we would make it as obvious as possible.

@OvermindDL1 Thanks, it is much appreciated, however as @ZirconiumX explained, it is possible that we would end up in the same situation again.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 Thanks, it is much appreciated, however as @ZirconiumX explained, it is possible that we would end up in the same situation again.

Understandable yep, though I do have a bit of a record, my servers have been hosting a variety of open source and community sites since 2000.  :-)

**Comment by mjones153** [comment]
Thank you very much.
