### ISSUE TITLE
Is there a way to verify the download?

### ISSUE THREAD

**Issue by mjones153** [mattanger/ckb-next#355]
Is there a way to verify the download with a checksum (such as sha512 or sha256)?  And is there a way to verify the signature of the checksum with gpg?

Thank you.

**Comment by Ravenslofty** [comment]
We just use git, so none of our downloads are signed, other than the internal verification that git itself uses.

**Comment by mjones153** [comment]
Ok, when I do download it, is there a way to verify that the download file succeeded with just a regular checksum? Thank you.

**Comment by Ravenslofty** [comment]
No. Only using the Git checksum.

**Comment by tatokis** [comment]
@mjones153 Unfortunately no.
If you use git to clone the repository, it will either be done through ssh or https, both of which are encrypted and prevent tampering between you and github.

Adding signed hashes on the releases is a good idea for the future, but currently our last release is outdated, so you might as well get a fresh copy from master.

If you really do desire, this is the sha512sum for the 0.2.8 release tarball, signed with the ckb-next PGP key that can be found in this repository.

Alternatively, I could upload a tar archive of the current master somewhere and sign the hash for that, but this is going to be more of a one shot.

**Comment by tatokis** [comment]
Looks like github didn't like that, hold on.

**Comment by tatokis** [comment]
Attached the signed hash. 
[sha512sum.txt](https://github.com/mattanger/ckb-next/files/1524241/sha512sum.txt)

**Comment by mjones153** [comment]
Thank you.

**Comment by mjones153** [comment]
One thing I should ask, what is the sha512 or sha256 sum for the current master.zip download?  Just as a way to double check on my end that the downloaded zip file has the right checksum.

**Comment by ghost** [comment]
> If you really do desire, this is the sha512sum for the 0.2.8 release tarball, signed with the ckb-next PGP key that can be found in this repository.

This is incorrect. The release was signed with my own [old] key, which is now revoked.

> One thing I should ask, what is the sha512 or sha256 sum for the current master.zip download?

sha256 is 772ee64e0dac094310f560dbf0b0ef274d531766415318f3c60f5beeaed0f8b8 as of e842da0183ed9fc757ad31f59d1ea776192559f2. But as @tatokis said, the Ss in HTTPS and SSH mean "secure", therefore, unless your whole system has already been compromised, a MITM cannot happen.

**Comment by ghost** [comment]
> If you really do desire, this is the sha512sum for the 0.2.8 release tarball, signed with the ckb-next PGP key that can be found in this repository.

Just to omit any confusion: in their message @tatokis meant a hand-signed archive and not the git tag in git history, so, what I said is irrelevant.

**Comment by mjones153** [comment]
Ah that makes sense.  With the SSH and HTTPS, is that only specific to cloning the repository, or does that apply to downloading the zip as well?

**Comment by Ravenslofty** [comment]
For the zip, too.

**Comment by mjones153** [comment]
Thank you.
