### ISSUE TITLE
[Long-term] Switch to URB Interrupts for all transfers

### ISSUE THREAD

**Issue by Ravenslofty** [mattanger/ckb-next#367]
## Boring technical stuff, TL;DR below
I'll begin with some context for those of you not on the IRC (@frickler24 comes to mind):

USB has four kinds of data transfer:
- Control, used mostly for setup and initialisation.
- Bulk, used for USB sticks and mass data transfer.
- Interrupt, used for keyboards and mice, mostly.
- Isochronous, used for USB sound cards.

Side note: to send a URB Interrupt through the Linux `ioctl` interfaces, you need to perform a single packet URB Bulk transfer. Don't ask why, I don't know either.

At the moment, for the Linux USB backend at least, we [send](https://github.com/mattanger/ckb-next/blob/master/src/ckb-daemon/usb_linux.c#L70-L77) URB Interrupts for write packets, but [send](https://github.com/mattanger/ckb-next/blob/master/src/ckb-daemon/usb_linux.c#L79-L80) and [receive](https://github.com/mattanger/ckb-next/blob/master/src/ckb-daemon/usb_linux.c#L141-L142) URB Controls for read packets. Meanwhile, an input thread [receives](https://github.com/mattanger/ckb-next/blob/master/src/ckb-daemon/usb_linux.c#L298-L311) URB Interrupts for input packets.

This worked fine for version 1 and 2 of the Corsair firmwares (excepting the [K95 Platinum](https://github.com/mattanger/ckb-next/issues/53#issuecomment-290994546)), but it seems a portion of version 3 firmwares (the K95P again, my M65 Pro) do not support Control transfers at all in software control mode. This means we need to switch to Interrupts for all packets.

Those of you paying attention may have noticed [the commented section in os_usbrecv](https://github.com/mattanger/ckb-next/blob/master/src/ckb-daemon/usb_linux.c#L132-L140), in particular, `This is what CUE does, but it doesn't seem to work on linux`.

On Saturday, I did some digging into why it doesn't work, and found that the reply packets were being received by the input thread, so the main thread that wished to receive an event would never get the packet.

This is an awkward problem, because it means we have to transfer data between threads, which is non-trivial.

## If you're not a techie, here's the TL;DR:
On firmware version 3 and the K95P, you won't be able to load stored settings on your device. For now we suggest you don't upgrade the firmware version, and bear with us.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/51
