### ISSUE TITLE
Want to help the ckb team but don't know how to code? Here are some things.

### ISSUE THREAD

**Issue by Ravenslofty** [mattanger/ckb-next#368]
### For all platforms
If you look through the code base, you'll find possibly badly phrased comments (lines beginning with `//`), such as [this one](https://github.com/mattanger/ckb-next/blob/master/src/ckb-daemon/usb_linux.c#L106). If you find those, open an issue about it and tag @ZirconiumX in it. I'll get it sorted and mention you in the commit.

You can also [join us in IRC](http://webchat.freenode.net/?channels=%23ckb-next&uio=d4) and say hello - it really makes our day.

### Linux
I've been trying to write a [specification](https://github.com/mattanger/ckb-next/wiki/Corsair-Protocol) for the corsair protocol, so we have a document to reference from. I could really use your help with it. If you enter IRC (link above), I can guide you through collecting data from your keyboard to further work on that.

### Windows (yes, really)
For a similar reason as above, we can use packet captures from CUE to work out how to add new devices, or see reference data. It's very useful.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/52
