### ISSUE TITLE
CKB-v0.2.8.pkg Keypress hold with mouse click not working unless reinstall after each reboot

### ISSUE THREAD

**Issue by kaekae84** [mattanger/ckb-next#373]
## What is the program's current behavior?

Mac OS Sierra + CKB-V0.2.8 + Corsair K95 RGB Keyboard.

Unable to perform shift/cmd/alt + click after each reboot. 

However, the function came back once I reinstall the pkg file. Takes only a short while but I was wondering if there's a process that was killed by the system upon reboot and I could just restart that? I tried looking for the daemon file that most of us are talking about here but I couldn't find it anywhere in the Activity Monitor. I tried killing all the other process (all auto restarts) and it doesn't work. Only reinstalling the pkg works.

I work with images and those mouse click + key hold functions are crucial to fast work procedures...

Any help will be appreciated! 

Many thanks in advance!
KK

**Comment by Kukuruts** [comment]
I have the same issue on High Sierra with a Corsair Strafe RGB.
I can also confirm that reinstalling the pkg works for the current session.

**Comment by kaekae84** [comment]
Does anyone know of a fix to this issue? Or is there anyone working on a solution? Is there a way I can learn to work on the code to get this straighten out too?

**Comment by Ravenslofty** [comment]
The team is currently split between trying to add K55 support, adding CMake, and ironing out the protocol documentation. If you want to get this fixed yourself, join us in IRC, and we'll try our best to guide you.

**Comment by Ravenslofty** [comment]
@tatokis has kindly informed me that the fix for this is already in Git master. You'll have to build ckb-next yourself, but that should fix it.

**Comment by kaekae84** [comment]
Oh wow. Thank you @ZirconiumX ! So good to know I can do something about it. How do I actually build CKB next? Is there a easy to follow guide? I am completely new to this and honestly just know how to open that PKG file and install. Hopefully I can get some guidance!

Thank you in advance every one!

**Comment by ghost** [comment]
@kaekae84 
> How do I actually build CKB next? Is there a easy to follow guide?

Follow the [README](https://github.com/mattanger/ckb-next#building-from-source).

**Comment by kaekae84** [comment]
@light2yellow thank you. I checked the read me and that’s where I got the link to download the MAC os version as per mentioned in my first post. It is CKB Version 0.2.8 right? 

It resolves the issue at the beginning of every install/reinstall but once you reboot, it undo the keyboard + mouse commands functions availability. 

Am I missing some configuration steps here to make it permanent?

Thank you,
Kae

**Comment by ghost** [comment]
@kaekae84 

as @ZirconiumX said, you'll have to compile the program. See [this](https://help.github.com/articles/cloning-a-repository/) to download the source code and follow the README - in the post above I linked to the section you are interested in.

**Comment by JesseVelden** [comment]
I had the same issue but rebuilding fixed it! 
Who can update the binaries on Github?
  
Edit: To compile CKB-next:
1. Download (and open to install command line tools) XCode and [Brew](https://brew.sh/)
2. Open up the terminal and use `brew install qt5`
3. `git clone https://github.com/mattanger/ckb-next`
3. `ckb-next/quickinstall` and follow the instructions

**Comment by kaekae84** [comment]
@ZirconiumX and @light2yellow thank you very much.:) with some fiddling around I managed it!

Does anyone know how I can update the binary? Perhaps I can make package of the new ckb next so people don’t have to compile it again?:)

**Comment by kaekae84** [comment]
@MegaCookie thank you! A RL Friend of mine who is here in git guided me through the process!:D
