### ISSUE TITLE
polaris (rgb mousepad)

### ISSUE THREAD

**Issue by Ashaxyn** [mattanger/ckb-next#377]
Corsair Polaris currently not supported by the driver, request for update. (packets capture sent on irc)

**Comment by ZirconiumX** [comment]
I've been working on this in the [mm800](https://github.com/ZirconiumX/ckb-next/tree/mm800) branch. If you dropped by on IRC again, we can then try to manually check that the daemon can talk to the Polaris.

**Comment by kkuehler** [comment]
Hi @Ashaxyn! When you get some time could you come back to the IRC channel and ping me (keur) or ZirconiumX. Unfortunately, none of us have a Polaris and we need to gather some more data before we can add driver support.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/55
