### ISSUE TITLE
Color Change Not Working

### ISSUE THREAD

**Issue by OSCrustacean** [mattanger/ckb-next#380]
I have both the K70 RGB RAPIDFIRE keyboard and the Harpoon mouse. I am on Fedora 27 and whenever I try to change the color of the animations the application freezes and crashes.

**Comment by Ravenslofty** [comment]
You've got the Qt colour picker bug, just like #319, #175, #70, #51, ccMSC/ckb#500, ccMSC/ckb#461.

The solution is [in the README](https://github.com/mattanger/ckb-next#fedora-26-color-changer-freeze-fix).
