### ISSUE TITLE
Monochrome icon

### ISSUE THREAD

**Issue by nazar-pc** [mattanger/ckb-next#382]
# Feature request

- [x] Yes
- [ ] No

A simple feature request: add an option to show monochrome tray icon (light/dark theme).

All other apps that show icon in my system are monochrome: qBittorrent, Nextcloud, Steam, Network indicator, etc. Would be nice if ckb-next can look similarly to the rest of icons.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/58
