### ISSUE TITLE
Disable driver for mouse (M65 Pro RGB)

### ISSUE THREAD

**Issue by bpx279** [mattanger/ckb-next#383]
Hello,

I have been using the driver on macOS High Sierra with my K70 RGB. It works reasonably well (sometimes the keyboard stops responding, but other than that, it works well). However, I purchased a M65 Pro RGB and the driver makes the mouse act very weird. About 75% of the time, when I press the middle button or any other button except left and right click, the mouse resets itself to the top left corner of the screen. Dragging while left clicking also does that.

Is there a way to disable the driver only for the mouse since it works fine when I unload the driver.

**Comment by tatokis** [comment]
Try the new pkg from https://github.com/ckb-next/ckb-next/releases
If that doesn't fix anything, you can get the source code, open usb.h and replace all instances of `1b2e` with an id for a device you do not have, such as `1d99`, and compile the code.

Other than that, there are https://github.com/ckb-next/ckb-next/issues/23 and https://github.com/ckb-next/ckb-next/issues/7 you can follow.
