### ISSUE TITLE
Pull Request merge progress.

### ISSUE THREAD

**Issue by tatokis** [mattanger/ckb-next#4]
This is a quick list to be used as a reference for which PRs have been merged from the original repository and which haven't.

* ~https://github.com/ccMSC/ckb/pull/541~
* ~https://github.com/ccMSC/ckb/pull/530~
* ~https://github.com/ccMSC/ckb/pull/516~
* ~https://github.com/ccMSC/ckb/pull/514~
* ~https://github.com/ccMSC/ckb/pull/511~
* ~https://github.com/ccMSC/ckb/pull/508~
* ~https://github.com/ccMSC/ckb/pull/507~
* ~https://github.com/ccMSC/ckb/pull/467~
* ~https://github.com/ccMSC/ckb/pull/455~
* ~https://github.com/ccMSC/ckb/pull/437~
* ~https://github.com/ccMSC/ckb/pull/403~
* ~https://github.com/ccMSC/ckb/pull/367~

You might notice that some pull requests are not listed here, despite being open.
That is because they were merged to the testing branch and then pulled into this fork.

**Comment by mattanger** [comment]
Gotcha. Thanks for the heads up.

**Comment by batchpert** [comment]
Hi its nice to see some progress finally being made on this :D however i don't know how you add these individual bits into the full ckb application. Any chance you could make a quick guide on what to do? I would be very grateful!!
Thanks

**Comment by tatokis** [comment]
I've brought newfx up to date, and I made some changes so that it compiles on linux.
Could someone test it (ckb-mviz) on linux?

Just want to be sure that it isn't a case of "it only works on my machine".

**Comment by fleischie** [comment]
@tatokis what needs to bei tested? I can check, whether it builds and the daemon/GUI starts without crashing. But I don't have my keyboard with me over the holidays.

**Comment by mattanger** [comment]
Yeah I can later today.

**Comment by tatokis** [comment]
Basically need to see if it compiles properly on other systems. And if 
possible, test it on a system that does not have pulseaudio.
It's supposed to check for libpulse simple and if it doesn't exist, 
ignore ckb-mviz completely.

**Comment by fleischie** [comment]
@tatokis Compiles and daemon + GUI runs (only basic settings, because of no keyboard).

I couldn't run `ckb-mviz` though, because (again) of no keyboard.

**Comment by tatokis** [comment]
Alright, thanks

**Comment by mattanger** [comment]
Builds find and works fine with my keyboard. I do have pulseaudio. I'll try to build it on a vm without pulse sometime today.

**Comment by tatokis** [comment]
Regarding ccMSC/ckb#508 do we merge it or not?
Otherwise this issue should be closed.

**Comment by tatokis** [comment]
`<l2y>	-f is a good thing, but that line should've changed since the PR was made and it's easier to just add it manually`

Fair enough point
