### ISSUE TITLE
Type lighting background colour

### ISSUE THREAD

**Issue by batchpert** [mattanger/ckb-next#63]
When setting the type lighting to any style where there is not a 0% opacity at the end of the gradient bar thing. e.g. the rainbow preset. The 100% colour is set as the background of the whole keyboard. The colours go back to how the actual background is once every key has been pressed but this isn't an very quick soloution.

**Comment by tatokis** [comment]
Sorry, just found your issue as I was going through the bug tracker.

I can't really understand what the problem is, could you elaborate a bit? Perhaps show some screenshots/screen captures.
