### ISSUE TITLE
where to download pkg

### ISSUE THREAD

**Issue by wdh1221cn** [mattanger/ckb-next#69]
I looked up every on the site, but I still could not find any link to down the pkg. Plz some one tell me where to find a pkg...

btw, I m using ckb beta-v0.2.6 which can not find my key board(k65 lux RGB). I hope I can find the right answer here.

gbl

**Comment by mattanger** [comment]
Hi, @wdh1221cn right now there are no binary packages available. We haven't reached a point where we're ready to release any packages. If you look at  https://github.com/mattanger/ckb-next/blob/master/README.md you can find instructions to install ckb-next manually. The contents section of the README will point you in the right direction for your particular operating system.

**Comment by ghost** [comment]
@wdh1221cn see https://github.com/mattanger/ckb-next/blob/master/README.md#current-status

**Comment by wdh1221cn** [comment]
Oh... you guys are awesome, those replies are damn quick.
tks all, I will try to install it manually, cheers.

downloading qt5, starting now.......


can't stop saying that you are awesome.
