### ISSUE TITLE
import/export

### ISSUE THREAD

**Issue by dkuida** [mattanger/ckb-next#74]
I consider creating the support for that, but before I start wanted to make sure if there is a magor blocker for that to work ? besides the tie needed I mean

**Comment by ghost** [comment]
As @frickler24 already said in ccMSC/ckb#574, the devs will appreciate any contribution as long as it's maintainable.

> if there is a magor blocker for that to work

I'm not able to answer this, maybe someone else could. You can also chat with the devs on #ckb-next irc channel.

**Comment by frickler24** [comment]
@dkuida I do not understand what you ment with import/export. Can you please explain your approach?

**Comment by fleischie** [comment]
@frickler24 I guess he means to write an import/export procedure for color/animation profiles.

@dkuida If you can provide a PR, that is based off of the latest ~master~ testing branch, that works as expected and ideally on mac and linux as well, then go ahead. :+1:

**Comment by ghost** [comment]
@fleischie I think it'd much better if @dkuida bases his PR against testing branch. This is written in the Readme and is generally a more healthy strategy because new features can not play well with the other new features.

**Comment by fleischie** [comment]
@light2yellow Yes, you may be right. I guess I was still under the impression, that the testing branch was not up to date as much. Anyway: Edited to say it's the testing branch and not the master branch. :smiley: :+1:

**Comment by Extarys** [comment]
Is there any word about this?
Also I cannot seem to find where the files are stored to import and export manually config files :D

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/6
