### ISSUE TITLE
I cant find the download ckb.pkg.

### ISSUE THREAD

**Issue by bryanchoi1994** [mattanger/ckb-next#76]
i dont know what should i download.
which one should i download please help me

**Comment by chicks-net** [comment]
This project is still being actively developed.  Building distribution packages is planned after development stabilizes.

**Comment by bryanchoi1994** [comment]
so should i use the old one ? ccMSC that one ? 
but my K65 RAPIDFIRE cannot be detected in that one 
I dont know how to fix it

**Comment by chicks-net** [comment]
See https://github.com/mattanger/ckb-next#current-status  It is currently a manual process.

**Comment by ericmalloff** [comment]
So what is the latest version of the build?  It looks as if 0.2.4 was last uploaded in Feb 2016 has this project been abandoned? 

I followed the instructions and installed release 0.2.4 (https://github.com/mattanger/ckb-next/releases) but the driver still does not seem to be working. I am not even sure if it replaced the old CKB driver I had installed. 

Looking forward to getting this up and running.

**Comment by mattanger** [comment]
The release versions are not accurate. There are no update to date binaries
currently. Please follow the manual install instructions in the readme.md. You can see the current status here: https://github.com/mattanger/ckb-next#current-status

**Comment by mattanger** [comment]
Again, please take a look at the `readme.md` for more information on how to install manually. If any issues building are encountered, please open a new issue.
