### ISSUE TITLE
Cannot build on macOS Sierra

### ISSUE THREAD

**Issue by tbcrawford-old** [mattanger/ckb-next#8]
When using `./qmake-auto && make` or building via Qt Creator, an error is reported that it cannot find Frameworks available on macOS Sierra. It starts at `Availability.h` but I'm quite positive that the error persists immediately after.

Here's what is shown after running `./qmake-auto && make`:

```
➜  ckb git:(master) ./qmake-auto && make
Info: creating stash file /Users/username/Documents/develop/github/ckb/.qmake.stash
cd src/ckb-daemon/ && ( test -e Makefile || /Users/username/Qt/5.7/clang_64/bin/qmake /Users/username/Documents/develop/github/ckb/src/ckb-daemon/ckb-daemon.pro -o Makefile ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.Debug
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c -std=gnu99 -Wno-unused-parameter -Werror=all -g -fPIC -DCKB_VERSION_STR=\"`cat /Users/username/Documents/develop/github/ckb/src/ckb-daemon/../../VERSION`\" -I. -I/Users/username/Qt/5.7/clang_64/mkspecs/macx-clang -o debug/device.o device.c
In file included from device.c:1:
In file included from ./command.h:4:
In file included from ./includes.h:4:
./os.h:47:10: fatal error: 'Availability.h' file not found
#include <Availability.h>
         ^
1 error generated.
make[2]: *** [debug/device.o] Error 1
make[1]: *** [debug] Error 2
make: *** [sub-src-ckb-daemon-make_first] Error 2
```

If anyone has an suggestions to fix this problem but does not have access to macOS Sierra, I can test it out. I'm just not familiar enough with qmake and Qt to debug this one unfortunately. I thought I had an idea of what could fix this problem by modifying something in `ckb-daemon.pro` after doing some tests with a new clean project, but couldn't duplicate this solution in this project unfortunately.

If you need anymore details about this, I'd be happy to assist in any way I can.

**Comment by tatokis** [comment]
Interesting.
Do you know if the file exists on your system?

A quick search here reveals that it should be in 
/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/Availability.h

It compiles fine for me on 10.12

**Comment by tbcrawford-old** [comment]
It is not available at that location. But I was able to find it at `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/Availability.h`

I am currently on my hackintosh testing this, but I'm sure this should not matter. I will check for this on my MacBook though.

**Comment by tatokis** [comment]
Considering the actual path is inside Xcode.app, I think XCode might not be installed properly on your system. Maybe it is not a bug after all, was quick to jump to conclusions.

Try reverting this commit locally and see if it compiles
https://github.com/mattanger/ckb/commit/b090356db9eb7d4bb1cf1d9e8255e04b176fdabd

**Comment by tbcrawford-old** [comment]
`Availability.h` still cannot be found.

Update: It appears this is available on my MacBook. I attempt to remove Xcode and all of its stray directories and reinstall. Hopefully something will get fixed there.

**Comment by tatokis** [comment]
Are you sure you modified the right file? There is no other reference of that file in ckb

**Comment by tbcrawford-old** [comment]
What modification are you referring to? I am still not seeing the header file at the location that you stated. I may end up attempting to reinstall Sierra if this persists.

**Comment by tatokis** [comment]
The only reference of Availability.h in ckb is inside os.h, and was introduced recently by commit https://github.com/mattanger/ckb/commit/b090356db9eb7d4bb1cf1d9e8255e04b176fdabd .

If you revert that commit, meaning you remove every trace of Availability.h from ckb, and it still fails to compile, then the problem is definitely not ckb.

Basically just comment out lines 47,73,74,75 in os.h

**Comment by tbcrawford-old** [comment]
I do believe I solved this. 
It appears that my `command-line-tools` may not have been properly installed or were not in the first place which I would find surprising. 
I was able to build and run now. Thank you for the help and working with me.

**Comment by tatokis** [comment]
Glad to hear it.

**Comment by tbcrawford-old** [comment]
@tatokis Would it be worth adding a small snippet to the OS X installation section of the README regarding ensuring that command-line-tools have been installed before building?

**Comment by tatokis** [comment]
It is part of XCode, isn't it?
If so, sure, submit a PR.

**Comment by tatokis** [comment]
Oh right, I remember getting a popup when installing XCode asking me to install the command line tools, and I installed it without thinking. Makes sense.

**Comment by tbcrawford-old** [comment]
Yeah. I did not see this popup when reinstalling or when I initially installed Xcode on my system. I do know however to install this since I develop other items though I do not believe a typical user would be aware of this. Would you like me to submit a PR for the README to include this instruction?

**Comment by tatokis** [comment]
Yeah, sure, go ahead.
