### ISSUE TITLE
New Mouse - Corsair CH-9301011-EU Harpoon

### ISSUE THREAD

**Issue by ghost** [mattanger/ckb-next#85]
Hi, just a request from me. Just wondered if you guys could add a new mouse to the software (Corsair CH-9301011-EU Harpoon). Anyway, if you can or can't thanks anyway really love the software :)
If I can help in any way, please ask and I will.

**Comment by ghost** [comment]
Hey. Run the `ckb-dev-detect` from the source code tree and upload the output. I suppose you're on Linux.

**Comment by ghost** [comment]
And if you're on macOS, then now you can provide the info following the instructions in #31 (see my last comment there, at the end).

**Comment by tatokis** [comment]
Duplicate of #54.
